# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c .cxx

include AD_MOBJECTS.h


OBJECTS = $(GB_O) $(GB_T) $(GB_PP)

$(MAIN): $(OBJECTS)
	$(AR) $(MAIN) $(OBJECTS)
.c.o:
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
.cxx.o:
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) *.c *.cxx
links:
	ln -s ../ARBDB/*.[ch] .

# DO NOT DELETE THIS LINE -- make depend depends on it.


adReference.o:  
adReference.o:  
adReference.o:  
adReference.o:  
adReference.o:  
adReference.o:  
adReference.o:   
adReference.o:  
adReference.o:  
adReference.o:  
adReference.o: 
adReference.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adReference.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adReference.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:   
adTest.o:   
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adTest.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adTest.o: ad_prot.h adlmacros.h adlocal.h admap.h adtune.h arbdb.h
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:   
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ad_core.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
ad_core.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:   
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:   
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
ad_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ad_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
ad_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
ad_load.o: ad_lpro.h ad_prot.h adlmacros.h adlocal.h admap.h adtune.h arbdb.h
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o: 
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o: 
ad_save_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
ad_save_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ad_save_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
ad_save_load.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
ad_save_load.o: ad_lpro.h ad_prot.h adlmacros.h adlocal.h admap.h adtune.h
ad_save_load.o: arbdb.h
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o:   
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o:   
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o:   
adcomm.o: 
adcomm.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
adcomm.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adcomm.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adcomm.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
adcomm.o: ad_lpro.h ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:   
adcompr.o:   
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adcompr.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adcompr.o: ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h adlocal.h adtune.h
adcompr.o: arbdb.h arbdbt.h
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:   
adhash.o:  
adhash.o:   
adhash.o:   
adhash.o:  
adhash.o:   
adhash.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adhash.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adhash.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:   
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adindex.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adindex.o: ad_prot.h adlmacros.h adlocal.h adlundo.h adtune.h arbdb.h
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:   
adlang1.o:   
adlang1.o:   
adlang1.o:  
adlang1.o:  
adlang1.o:   
adlang1.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adlang1.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adlang1.o: ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h adlocal.h adtune.h
adlang1.o: arbdb.h arbdbt.h
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:   
adlink.o:  
adlink.o:  
adlink.o:   
adlink.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adlink.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adlink.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:   
admalloc.o:  
admalloc.o:  
admalloc.o:   
admalloc.o: 
admalloc.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
admalloc.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
admalloc.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
admalloc.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
admalloc.o: ad_lpro.h ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
admap.o:  
admap.o:  
admap.o:  
admap.o:  
admap.o:  
admap.o:   
admap.o:   
admap.o:  
admap.o:  
admap.o:  
admap.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
admap.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
admap.o: ad_prot.h adlmacros.h adlocal.h admap.h adtune.h arbdb.h
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:   
admath.o:   
admath.o:  
admath.o:  
admath.o:  
admath.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
admath.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
admath.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
admath.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:   
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
adoptimize.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adoptimize.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adoptimize.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
adoptimize.o: ad_lpro.h ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:   
adperl.o:  
adperl.o:  
adperl.o:   
adperl.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adperl.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_prot.h
adperl.o: arbdb.h
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:   
adquery.o:   
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adquery.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adquery.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:   
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adseqcompr.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adseqcompr.o: ad_lpro.h ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h
adseqcompr.o: adlocal.h adseqcompr.h adtune.h arbdb.h arbdbt.h
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:   
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:   
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:   
adsocket.o:  
adsocket.o: 
adsocket.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
adsocket.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adsocket.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adsocket.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
adsocket.o: ad_lpro.h ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:   
adsort.o:   
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adsort.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_prot.h
adsort.o: ad_t_prot.h arbdb.h arbdbt.h
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:   
adstring.o:  
adstring.o:  
adstring.o:   
adstring.o: 
adstring.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adstring.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adstring.o: ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h adlocal.h adtune.h
adstring.o: arbdb.h arbdbt.h
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:   
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o: 
adsystem.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
adsystem.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adsystem.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adsystem.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
adsystem.o: ad_lpro.h ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h adlocal.h
adsystem.o: adtune.h arbdb.h arbdbt.h
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:   
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o: 
adtables.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adtables.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adtables.o: ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h adlocal.h adtune.h
adtables.o: arbdb.h arbdbt.h
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:   
adtools.o:   
adtools.o:   
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
adtools.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adtools.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ad_lpro.h
adtools.o: ad_prot.h ad_t_lpro.h ad_t_prot.h adlmacros.h adlocal.h adtune.h
adtools.o: arbdb.h arbdbt.h
adtune.o: adtune.h
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:   
arbdb.o:  
arbdb.o:  
arbdb.o:   
arbdb.o:   
arbdb.o:  
arbdb.o:  
arbdb.o:   
arbdb.o: 
arbdb.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
arbdb.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
arbdb.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
arbdb.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h ad_lpro.h
arbdb.o: ad_prot.h adlmacros.h adlocal.h adtune.h arbdb.h
arbdbpp.c.o:  
arbdbpp.c.o:  
arbdbpp.c.o:  
arbdbpp.c.o:  
arbdbpp.c.o:  
arbdbpp.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
arbdbpp.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
arbdbpp.c.o: ad_prot.h ad_t_prot.h arbdb.h arbdbt.h
