# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx


CPP_OBJECTS =  SEER_main.o SEER_interface.o SEER_connect.o SEER_arb.o SEER_to_seer.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)



.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

SEER_main.o:  
SEER_main.o:  
SEER_main.o:  
SEER_main.o:  
SEER_main.o:  
SEER_main.o: 
SEER_main.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_main.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_main.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_main.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_main.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/awt.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/awt_dtree.hxx
SEER_main.o: $(ARBHOME)/INCLUDE/ntree.hxx seer.hxx
SEER_main.o: seer_interface.hxx
SEER_interface.o:  
SEER_interface.o:  
SEER_interface.o:  
SEER_interface.o: 
SEER_interface.o:  
SEER_interface.o:  
SEER_interface.o:  
SEER_interface.o:  
SEER_interface.o:  seer_interface.hxx
SEER_connect.o: 
SEER_connect.o:  
SEER_connect.o:  
SEER_connect.o:  
SEER_connect.o:  
SEER_connect.o:  
SEER_connect.o: 
SEER_connect.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_connect.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_connect.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_connect.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_connect.o: $(ARBHOME)/INCLUDE/aw_root.hxx seer.hxx
SEER_connect.o: seer_interface.hxx
SEER_arb.o: 
SEER_arb.o:  
SEER_arb.o:  
SEER_arb.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_arb.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_arb.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_arb.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_arb.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_arb.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEER_arb.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEER_arb.o: $(ARBHOME)/INCLUDE/awt.hxx
SEER_arb.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEER_arb.o: $(ARBHOME)/INCLUDE/ntree.hxx seer.hxx
SEER_arb.o: seer_interface.hxx
SEER_to_seer.o: 
SEER_to_seer.o:  
SEER_to_seer.o:  
SEER_to_seer.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_to_seer.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_to_seer.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_to_seer.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_to_seer.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_to_seer.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEER_to_seer.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEER_to_seer.o: $(ARBHOME)/INCLUDE/awt.hxx
SEER_to_seer.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEER_to_seer.o: $(ARBHOME)/INCLUDE/ntree.hxx seer.hxx
SEER_to_seer.o: seer_interface.hxx
