# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS =  PARS_main.o PARS_dtree.o PARS_debug.o PARS_klprops.o AP_buffer.o AP_main.o AP_tree_nlen.o AP_tree_edge.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)

# DO NOT DELETE THIS LINE -- make depend depends on it.


AP_buffer.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AP_buffer.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AP_buffer.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AP_buffer.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AP_buffer.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
AP_buffer.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
AP_buffer.c.o:  
AP_buffer.c.o:  
AP_buffer.c.o:  
AP_buffer.c.o:  
AP_buffer.c.o:  
AP_buffer.c.o:  
AP_buffer.c.o:  
AP_buffer.c.o: 
AP_buffer.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AP_buffer.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AP_buffer.c.o: AP_buffer.hxx AP_error.hxx
AP_main.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AP_main.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AP_main.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AP_main.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AP_main.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
AP_main.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o:   
AP_main.c.o:  
AP_main.c.o:  
AP_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AP_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AP_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AP_main.c.o: AP_buffer.hxx AP_error.hxx parsimony.hxx
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
AP_tree_edge.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o: 
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o:  
AP_tree_edge.c.o: 
AP_tree_edge.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AP_tree_edge.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
AP_tree_edge.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AP_tree_edge.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AP_tree_edge.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
AP_tree_edge.c.o: AP_buffer.hxx ap_tree_nlen.hxx parsimony.hxx
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
AP_tree_nlen.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o: 
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o:  
AP_tree_nlen.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AP_tree_nlen.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
AP_tree_nlen.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AP_tree_nlen.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AP_tree_nlen.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
AP_tree_nlen.c.o: AP_buffer.hxx ap_tree_nlen.hxx pars_debug.hxx parsimony.hxx
PARS_debug.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PARS_debug.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PARS_debug.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PARS_debug.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PARS_debug.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o:  
PARS_debug.c.o: 
PARS_debug.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PARS_debug.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PARS_debug.c.o: pars_debug.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_csp.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_dtree.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_seq_protein.hxx
PARS_dtree.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o: 
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o:  
PARS_dtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
PARS_dtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PARS_dtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PARS_dtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
PARS_dtree.c.o: AP_buffer.hxx ap_tree_nlen.hxx pars_debug.hxx pars_dtree.hxx
PARS_dtree.c.o: pars_main.hxx parsimony.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt_dtree.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PARS_klprops.c.o: $(ARBHOME)/INCLUDE/awt_tree_cb.hxx
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o: 
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o:  
PARS_klprops.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
PARS_klprops.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PARS_klprops.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PARS_klprops.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
PARS_klprops.c.o: AP_buffer.hxx ap_tree_nlen.hxx pars_dtree.hxx pars_main.hxx
PARS_klprops.c.o: parsimony.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PARS_main.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PARS_main.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PARS_main.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PARS_main.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_csp.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_dtree.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PARS_main.c.o: $(ARBHOME)/INCLUDE/awt_tree_cb.hxx
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o:  
PARS_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
PARS_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PARS_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PARS_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
PARS_main.c.o: AP_buffer.hxx ap_tree_nlen.hxx pars_dtree.hxx pars_main.hxx
PARS_main.c.o: parsimony.hxx
