.SUFFIXES: .o .c

LIBS    = -lm -lc
PROGS   =          clique coallike consense contml contrast dnacomp dnadist \
                   dnainvar dnaml dnamlk dnamove dnapars dnapenny \
                   dolmove dollop dolpenny drawgram drawtree factor \
                   fitch gendist kitsch mix move neighbor penny \
                   protdist protpars restml retree seqboot

all:	$(PROGS:%=../../bin/%)

../../bin/dnaml:        dnaml.o dnaml2.o
	$(ACC) $(cflags) -o $@ dnaml.o dnaml2.o $(LIBS)

../../bin/dnamlk:       dnamlk.o dnamlk2.o
	$(ACC) $(cflags) -o $@ dnamlk.o dnamlk2.o $(LIBS)

../../bin/drawgram:     drawgram.o drawgraphics.o
	$(ACC) $(cflags) -o $@ drawgram.o drawgraphics.o $(LIBS)

../../bin/drawtree:     drawtree.o drawgraphics.o
	$(ACC) $(cflags) -o $@ drawtree.o drawgraphics.o $(LIBS)

../../bin/mix:     mix.o mix2.o
	$(ACC) $(cflags) -o $@ mix.o mix2.o $(LIBS)

../../bin/restml:     restml.o restml2.o
	$(ACC) $(cflags) -o $@ restml.o restml2.o $(LIBS)

../../bin/protml:     protml.o p2clib.o
	$(ACC) $(cflags) -o $@ protml.o p2clib.o $(LIBS)

../../bin/%: %.c
	$(ACC) $(cflags) -o $@ $< $(LIBS)

.c.o :
	$(ACC) -c $(cflags) $<

depend:
	makedepend $(MAKEDEPENDINC) -p ../../bin/ $(PROGS:%=%.c)

clean:
	@rm $(PROGS) *.o
# DO NOT DELETE THIS LINE -- make depend depends on it.


clique.o:  
clique.o:  
clique.o:  
clique.o:  
clique.o:  
clique.o:  
clique.o:   
clique.o:  
clique.o:   
clique.o:   
clique.o:  
clique.o:   
clique.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
clique.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
clique.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o:   
coallike.o:   
coallike.o:  
coallike.o:  
coallike.o:  
coallike.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
coallike.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
coallike.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
consense.o:  
consense.o:  
consense.o:  
consense.o:  
consense.o:  
consense.o:  
consense.o:  
consense.o:  
consense.o:   
consense.o:   
consense.o:  
consense.o:  
consense.o:  
consense.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
consense.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
consense.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
contml.o:  
contml.o:  
contml.o:  
contml.o:  
contml.o:  
contml.o:  
contml.o:   
contml.o:  
contml.o:   
contml.o:   
contml.o:  
contml.o:   
contml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
contml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
contml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o:   
contrast.o:   
contrast.o:  
contrast.o:  
contrast.o:  
contrast.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
contrast.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
contrast.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o:   
dnacomp.o:   
dnacomp.o:  
dnacomp.o:  
dnacomp.o:  
dnacomp.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnacomp.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnacomp.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o:   
dnadist.o:   
dnadist.o:  
dnadist.o:  
dnadist.o:  
dnadist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnadist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnadist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o:   
dnainvar.o:   
dnainvar.o:  
dnainvar.o:  
dnainvar.o:  
dnainvar.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnainvar.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnainvar.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnaml.o:  
dnaml.o:  
dnaml.o:  
dnaml.o:  
dnaml.o:  
dnaml.o:  
dnaml.o:   
dnaml.o:   
dnaml.o:   
dnaml.o:  
dnaml.o:  
dnaml.o:   
dnaml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnaml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnaml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnamlk.o:  
dnamlk.o:  
dnamlk.o:  
dnamlk.o:  
dnamlk.o:  
dnamlk.o:  
dnamlk.o:   
dnamlk.o:  
dnamlk.o:   
dnamlk.o:   
dnamlk.o:  
dnamlk.o:   
dnamlk.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnamlk.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnamlk.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o:   
dnamove.o:   
dnamove.o:  
dnamove.o:  
dnamove.o:  
dnamove.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnamove.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnamove.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o:   
dnapars.o:   
dnapars.o:  
dnapars.o:  
dnapars.o:  
dnapars.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnapars.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnapars.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o:   
dnapenny.o:   
dnapenny.o:  
dnapenny.o:  
dnapenny.o:  
dnapenny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dnapenny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dnapenny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dollop.o:  
dollop.o:  
dollop.o:  
dollop.o:  
dollop.o:  
dollop.o:  
dollop.o:   
dollop.o:  
dollop.o:   
dollop.o:   
dollop.o:  
dollop.o:   
dollop.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dollop.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dollop.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o:   
dolmove.o:   
dolmove.o:  
dolmove.o:  
dolmove.o:  
dolmove.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dolmove.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dolmove.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o:   
dolpenny.o:   
dolpenny.o:  
dolpenny.o:  
dolpenny.o:  
dolpenny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
dolpenny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
dolpenny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o:   
drawgram.o:   
drawgram.o:  
drawgram.o:  
drawgram.o:  
drawgram.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
drawgram.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
drawgram.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
drawgram.o: drawgraphics.h phylip.h
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o:   
drawtree.o:   
drawtree.o:  
drawtree.o:  
drawtree.o:  
drawtree.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
drawtree.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
drawtree.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
drawtree.o: drawgraphics.h phylip.h
factor.o:  
factor.o:  
factor.o:  
factor.o:  
factor.o:  
factor.o:  
factor.o:   
factor.o:  
factor.o:   
factor.o:   
factor.o:  
factor.o:   
factor.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
factor.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
factor.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
fitch.o:  
fitch.o:  
fitch.o:  
fitch.o:  
fitch.o:  
fitch.o:  
fitch.o:   
fitch.o:   
fitch.o:   
fitch.o:  
fitch.o:  
fitch.o:   
fitch.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
fitch.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
fitch.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o:   
gendist.o:   
gendist.o:  
gendist.o:  
gendist.o:  
gendist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
gendist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
gendist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
kitsch.o:  
kitsch.o:  
kitsch.o:  
kitsch.o:  
kitsch.o:  
kitsch.o:  
kitsch.o:   
kitsch.o:  
kitsch.o:   
kitsch.o:   
kitsch.o:  
kitsch.o:   
kitsch.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
kitsch.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
kitsch.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
mix.o:  
mix.o:  
mix.o:  
mix.o:  
mix.o:  
mix.o:  
mix.o:   
mix.o:   
mix.o:   
mix.o:  
mix.o:  
mix.o:   
mix.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
mix.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
mix.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
move.o:  
move.o:  
move.o:  
move.o:  
move.o:  
move.o:  
move.o:   
move.o:   
move.o:   
move.o:  
move.o:  
move.o:   
move.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
move.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
move.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o:   
neighbor.o:   
neighbor.o:  
neighbor.o:  
neighbor.o:  
neighbor.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
neighbor.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
neighbor.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
penny.o:  
penny.o:  
penny.o:  
penny.o:  
penny.o:  
penny.o:  
penny.o:   
penny.o:   
penny.o:   
penny.o:  
penny.o:  
penny.o:   
penny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
penny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
penny.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o:   
protdist.o:   
protdist.o:  
protdist.o:  
protdist.o:  
protdist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
protdist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
protdist.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o:   
protpars.o:   
protpars.o:  
protpars.o:  
protpars.o:  
protpars.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
protpars.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
protpars.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
restml.o:  
restml.o:  
restml.o:  
restml.o:  
restml.o:  
restml.o:  
restml.o:   
restml.o:  
restml.o:   
restml.o:   
restml.o:  
restml.o:   
restml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
restml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
restml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
retree.o:  
retree.o:  
retree.o:  
retree.o:  
retree.o:  
retree.o:  
retree.o:   
retree.o:  
retree.o:   
retree.o:   
retree.o:  
retree.o:   
retree.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
retree.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
retree.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o:   
seqboot.o:   
seqboot.o:  
seqboot.o:  
seqboot.o:  
seqboot.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
seqboot.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
seqboot.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h phylip.h
