#!/bin/sh
cd ..
ARBMETA=`pwd`
dest=""
for file in *; do
	if  test -d $file -a "$file" != source; then
		dest="${dest} ${ARBMETA}/${file}"
	fi
done

echo "Destination(s):" $dest

echo $ARBMETA/source/util/arb_update_copy $ARBMETA/source $dest
$ARBMETA/source/util/arb_update_copy $ARBMETA/source $dest
#arb_update_copy $ARBMETA/source -host hp8 arb
