# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS = demo.o
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o: 
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


demo.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
demo.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
demo.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
demo.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
demo.c.o:  
demo.c.o:  
demo.c.o:  
demo.c.o:  
demo.c.o:  
demo.c.o:  
demo.c.o:   
demo.c.o:   
demo.c.o:  
demo.c.o:  
demo.c.o:  
demo.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
demo.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h demo.hxx
