# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS = demo.o
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o: 
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

demo.o:   
demo.o:  
demo.o:  
demo.o:  
demo.o:   
demo.o:  
demo.o:  
demo.o:  
demo.o: $(ARBHOME)/INCLUDE/aw_root.hxx
demo.o: $(ARBHOME)/INCLUDE/aw_device.hxx
demo.o: $(ARBHOME)/INCLUDE/aw_window.hxx
demo.o: $(ARBHOME)/INCLUDE/aw_preset.hxx ./demo.hxx
demo.o:   
