      cl_alifnm = ' '
      cl_binfnm = ' '
      cl_outfnm = ' '
      cl_errfnm = ' '
      cl_newfnm = ' ' 
      cl_logfnm = ' '
      cl_namfnm = ' ' 
      cl_addfnm = ' '

      cl_alilun = 1
      cl_newlun = 2
      cl_binlun = 3
      cl_loglun = 4
      cl_outlun = 7
      cl_errlun = 9
      cl_namlun = 10
      cl_addlun = 11

      cl_aliflag = .FALSE.
      cl_binflag = .FALSE.
      cl_outflag = .FALSE.
      cl_errflag = .FALSE.
      cl_newflag = .FALSE.
      cl_logflag = .FALSE.
      cl_namflag = .FALSE.
      cl_addflag = .FALSE.

      cl_listflag = .FALSE.
      cl_chimflag = .FALSE.
      cl_simpflag = .FALSE.
      cl_fragflag = .FALSE.
      cl_partflag = .FALSE.

      cl_listlen = 20
      cl_outwid = 78
      cl_steplen = 10
      cl_fraglen = 10
      cl_partlen = 50
      cl_tuplen = 7
