# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx

CPP_OBJECTS =   CAT_tree.o 

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:  
CAT_tree.o:   
CAT_tree.o: $(ARBHOME)/INCLUDE/arbdb.h
CAT_tree.o: $(ARBHOME)/INCLUDE/ad_prot.h
CAT_tree.o: $(ARBHOME)/INCLUDE/arbdbt.h
CAT_tree.o: $(ARBHOME)/INCLUDE/ad_t_prot.h cat_tree.hxx
