#!/bin/sh
  gunzip -c arbsrc*.tgz |tar xvf -
#  zcat arbsrc*.tgz |cpio -imvdH tar

# for some machines comment the first line and uncomment the next
mkdir -p PROBE_COM/GENH
mkdir -p PROBE_COM/GENC
mkdir -p PROBE_COM/O
mkdir -p MGR_COM/GENH
mkdir -p MGR_COM/GENC
mkdir -p MGR_COM/O
mkdir -p NAMES_COM/GENH
mkdir -p NAMES_COM/GENC
mkdir -p NAMES_COM/O
mkdir -p ORS_COM/GENH
mkdir -p ORS_COM/GENC
mkdir -p ORS_COM/O
mkdir -p MAKEBIN
mkdir -p DEPOT
mkdir -p PERL5
mkdir -p PERL5/bin
mkdir -p cgi-bin


if test ! -d lib/pts; then
	mkdir -p lib/pts
fi

(cd DUMMYINC; ln -s . xview);
# create symlinks in lib dir
(cd lib;make);
(cd bin;make all);
touch timestamp

#try to find gzip
cp -p `which gzip` zcat
