LIB = -L../LIBLINK -lARBDO $(SYSLIBS)

OBJECT = io_arbdb.o getopt.o getopt1.o xmalloc.o lenstring.o careful.o

.SUFFIXES: .o .c .cxx

all: $(ARBHOME)/bin/arb_aleio

$(ARBHOME)/bin/arb_aleio:  $(OBJECT)
	$(ACC) $(cflags) -o $@ $(OBJECT)  $(LIB)

.c.o:
	$(ACC) $(cflags) -c $< $(AINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJECT:.o=.c*)

# DO NOT DELETE THIS LINE -- make depend depends on it.


careful.o:  
careful.o:  
careful.o:  
careful.o:  
careful.o:  
careful.o:  
careful.o:   
careful.o: 
careful.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
careful.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
getopt.o:  
getopt.o:  
getopt.o:  
getopt.o:   
getopt.o:  
getopt.o: 
getopt.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
getopt.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
getopt1.o:  
getopt1.o:  
getopt1.o:  
getopt1.o:   
getopt1.o: 
getopt1.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
getopt1.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h getopt.h
io_arbdb.o: $(ARBHOME)/INCLUDE/ad_prot.h
io_arbdb.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
io_arbdb.o: $(ARBHOME)/INCLUDE/arbdb.h
io_arbdb.o: $(ARBHOME)/INCLUDE/arbdbt.h
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o:   
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o:  
io_arbdb.o: 
io_arbdb.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
io_arbdb.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h careful.h
io_arbdb.o: getopt.h hash.h lenstring.h ring.h xmalloc.h
lenstring.o:  
lenstring.o:  
lenstring.o:  
lenstring.o:  
lenstring.o:  
lenstring.o:  
lenstring.o:   
lenstring.o:  
lenstring.o:  
lenstring.o:  
lenstring.o: 
lenstring.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
lenstring.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
lenstring.o: lenstring.h xmalloc.h
xmalloc.o:  
xmalloc.o:  
xmalloc.o:  
xmalloc.o:  
xmalloc.o:  
xmalloc.o:  
xmalloc.o:   
xmalloc.o:  
xmalloc.o:  
xmalloc.o:  
xmalloc.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
xmalloc.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h xmalloc.h
