#!/bin/bash -x

if [ -z "$6" ]; then
    echo "Usage: arb_dnapars bootstrap searchdepth viewreport randomize stepcount threshold"
else
    BOOTSTRAP=$1
    SEARCH=$2
    REPORT=$3
    RANDOMIZE=$4
    STEPCOUNT=$5
    THRESHOLD=$6

    FLAGS=

    if [ "$RANDOMIZE" = "1" ]; then
        RANDOMSEED=$(($RANDOM|1)) # a odd number
        FLAGS="$FLAGS j $RANDOMSEED 1"
    fi

    if [ "$STEPCOUNT" = "0" ]; then
        FLAGS="$FLAGS n"
    fi

    if [ \! "$THRESHOLD" = "0" ]; then
        FLAGS="$FLAGS t $THRESHOLD"
    fi

    case $SEARCH in
        0) FLAGS="$FLAGS" ;;
        1) FLAGS="$FLAGS s n" ;;
        2) FLAGS="$FLAGS s y" ;;
        *)  echo "Illegal value for 'searchdepth'"; exit 1 ;;
    esac

    if [ "$BOOTSTRAP" = "0" ]; then
        arb_echo $FLAGS y | dnapars
        #dnapars
        echo >arb_read_tree_args
        WHAT=dnapars
    else
        arb_bootstrap $BOOTSTRAP dnapars $FLAGS
        WHAT=arb_bootstrap/dnapars/consense
    fi

    if [ -f outfile ]; then
        if [ -s outfile ]; then
            if [ "$REPORT" = "1" ]; then
                arb_textedit outfile &
            fi
        else
            echo "$WHAT: Warning: generated 'outfile' is empty"
        fi
    else
        echo "$WHAT: Warning: 'outfile' was not created"
    fi
fi
