#!/bin/sh
# usage: arb_bootstrap count count2 treeprog
# 'count' is passed to treeprog
# 'count2' is passed to arb_readtree (bootstrap values are devided by count2)
# 'treeprog' calculates the trees (e.g. dnapars, protpars)

echo "-consense $2" >arb_read_tree_args

arb_echo "1 r $1 y" | seqboot
/bin/mv -f outfile infile

arb_wait

arb_echo "m $1 y" | $3
/bin/mv -f treefile infile

arb_wait

arb_echo y | consense

arb_wait

arb_textedit outfile &

