#!/bin/bash -x

if [ -z "$5" ]; then
    echo "Usage: arb_protpars bootstrap geneticcode viewreport randomize threshold"
else
    BOOTSTRAP=$1
    CODE=$2
    REPORT=$3
    RANDOMIZE=$4
    THRESHOLD=$5

    FLAGS="c $CODE"

    if [ "$RANDOMIZE" = "1" ]; then
        RANDOMSEED=$(($RANDOM|1)) # a odd number
        FLAGS="$FLAGS j $RANDOMSEED 1"
    fi

    if [ \! "$THRESHOLD" = "0" ]; then
        FLAGS="$FLAGS t $THRESHOLD"
    fi

    if [ "$BOOTSTRAP" = "0" ]; then
        arb_echo $FLAGS y | protpars
        #protpars
        echo >arb_read_tree_args
        WHAT=protpars
    else
        arb_bootstrap $BOOTSTRAP protpars $FLAGS
        WHAT=arb_bootstrap/protpars/consense
    fi

    if [ -f outfile ]; then
        if [ -s outfile ]; then
            if [ "$REPORT" = "1" ]; then
                arb_textedit outfile &
            fi
        else
            echo "$WHAT: Warning: generated 'outfile' is empty"
        fi
    else
        echo "$WHAT: Warning: 'outfile' was not created"
    fi
fi
