#!/bin/bash -x

if [ -z "$6" ]; then
    echo "Usage: arb_proml bootstrap aachangemodel viewreport analysis randomize rearrange"
else
    BOOTSTRAP=$1
    MODEL=$2
    REPORT=$3
    ANALYSIS=$4
    RANDOMIZE=$5
    REARRANGE=$6

    FLAGS=""

    if [ "$MODEL" = "PAM" ]; then
        FLAGS="$FLAGS p"
    fi
    if [ "$ANALYSIS" = "fine" ]; then
        FLAGS="$FLAGS s"
    fi
    if [ "$RANDOMIZE" = "1" ]; then
        RANDOMSEED=$(($RANDOM|1)) # a odd number
        FLAGS="$FLAGS j $RANDOMSEED 1"
    fi
    if [ "$REARRANGE" = "1" ]; then
        FLAGS="$FLAGS g"
    fi

#     if [ \! "$THRESHOLD" = "0" ]; then
#         FLAGS="$FLAGS t $THRESHOLD"
#     fi

    if [ "$BOOTSTRAP" = "0" ]; then
        arb_echo $FLAGS y | proml
        #proml
        echo >arb_read_tree_args
        WHAT=proml
    else
        arb_bootstrap $BOOTSTRAP proml $FLAGS
        WHAT=arb_bootstrap/proml/consense
    fi

    if [ -f outfile ]; then
        if [ -s outfile ]; then
            if [ "$REPORT" = "1" ]; then
                arb_textedit outfile &
            fi
        else
            echo "$WHAT: Warning: generated 'outfile' is empty"
        fi
    else
        echo "$WHAT: Warning: 'outfile' was not created"
    fi
fi
