#!/bin/bash -x
# usage: arb_protml opt1 opt2 phylip_input [no_of_bootstrap_trees]
# 'opt1' and 'opt2' are options to protml
# renames output to 'treefile'

if [ -f treefile ]; then
    rm treefile
fi

if [ -z "$3" ]; then
    echo "Wrong arguments for arb_protml"
else
    if [ \! -s $3 ]; then
        echo "Error: no or empty input file"
        ls -al $3
    else
        if [ -z "$4" ]; then
            # normal tree generation with protml
            protml $1 $2 -v -I $3
            if [ \! -f protml.tre ]; then
                echo "Error running protml: protml.tre not generated"
            else
                mv protml.tre treefile
            fi
        else
            # bootstrapping:

            # geht nicht:
            #
            # protml -I -jf -q -n 100 /tmp/gde137_0.in > firstpass.quickadd
            # protml -I -jf -u -v /tmp/gde137_0.in firstpass.quickadd
            #
            # funktioniert:
            #
            # protml -I -jf -e -n 100 /tmp/gde137_0.in > firstpass.exhaustive
            # protml -I -jf -u -v /tmp/gde137_0.in firstpass.exhaustive
            #

            protml $1 $2 -n $4 -I $3 > outfile
            less outfile
            if [ -s outfile ]; then
                echo "Error running protml: outfile not generated"
            else
                protml $1 -u -v -I $3 outfile

                if [ \! -f protml.tre ]; then
                    echo "Error running protml: protml.tre not generated"
                else
                    LINES=`wc -l <protml.tre`
                    LINES=$(($LINES-1))
                    tail -n $LINES <protml.tre >treefile
                fi
            fi
        fi
    fi
fi

