# Makefile May 2004 by Alexandros P. Stamatakis

CC = pgcc 

CFLAGS =  -O3 -DNORMAL
CFLAGS_OMP = -O3 -DOPEN_MP -mp
#CFLAGS_MKL =  -O3 -DMKL -fomit-frame-pointer -funroll-loops

RM = rm -f

all : raxml consense raxmlOMP #raxmlMKL

consense : consense.o cons.o phylip.o
	$(CC) $(CFLAGS)	-o consense -lm consense.o phylip.o cons.o

raxml :  axml.o dnapars.o rev_functions.o 
	$(CC) $(CFLAGS) -o  raxml.p axml.o dnapars.o rev_functions.o -lm 

raxmlOMP :axmlOMP.o dnaparsOMP.o rev_functions.o
	$(CC) $(CFLAGS_OMP) -o raxmlOMP.p axmlOMP.o dnaparsOMP.o rev_functions.o -lm

raxmlMKL : axmlMKL.o dnapars.o rev_functions.o 
	$(CC) $(CFLAGS_MKL) -o  raxmlMKL axmlMKL.o dnapars.o rev_functions.o -lm 

rev_functions.o : rev_functions.c
	$(CC) -c  rev_functions.c -o rev_functions.o 

consense.o : consense.c cons.h phylip.h
	$(CC) $(CFLAGS) -c consense.c


cons.o : cons.c cons.h phylip.h
	$(CC) $(CFLAGS) -c cons.c

phylip.o : phylip.c phylip.h
	$(CC) $(CFLAGS) -c phylip.c

axml.o : axml.c axml.h
	$(CC) $(CFLAGS) -c  axml.c -o axml.o

axmlOMP.o : axml.c axml.h
	$(CC) $(CFLAGS_OMP)  -c  axml.c -o axmlOMP.o

axmlMKL.o : axml.c axml.h
	$(CC) $(CFLAGS_MKL)  -c  axml.c -o axmlMKL.o

dnapars.o : dnapars.c phylip2.h
	$(CC) $(CFLAGS) -c dnapars.c 

dnaparsOMP.o : dnapars.c phylip2.h
	$(CC) $(CFLAGS_OMP) -c dnapars.c -o dnaparsOMP.o


clean : 
	$(RM) *.o
	$(RM) raxml.p raxmlOMP.p consense
