# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS =   GDE_ParseMenu.o GDE.o GDE_event.o \
	GDE_arbdb_io.o  GDE_HGLfile.o\
	GDE_Genbank.o GDE_FileIO.o 
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


GDE.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
GDE.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
GDE.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE.c.o: $(ARBHOME)/INCLUDE/awt.hxx 
GDE.c.o:  
GDE.c.o:  
GDE.c.o:  
GDE.c.o:  
GDE.c.o:  
GDE.c.o:   
GDE.c.o:   
GDE.c.o:  
GDE.c.o:  
GDE.c.o:  
GDE.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h GDE_def.h
GDE.c.o: GDE_extglob.h GDE_menu.h gde.hxx
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE_FileIO.c.o: $(ARBHOME)/INCLUDE/awt.hxx
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o:  
GDE_FileIO.c.o: 
GDE_FileIO.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE_FileIO.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
GDE_FileIO.c.o: GDE_def.h GDE_extglob.h GDE_menu.h gde.hxx
GDE_Genbank.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE_Genbank.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE_Genbank.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE_Genbank.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE_Genbank.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE_Genbank.c.o: $(ARBHOME)/INCLUDE/awt.hxx
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o:  
GDE_Genbank.c.o: 
GDE_Genbank.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE_Genbank.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
GDE_Genbank.c.o: GDE_def.h GDE_extglob.h GDE_menu.h gde.hxx
GDE_HGLfile.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE_HGLfile.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE_HGLfile.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE_HGLfile.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE_HGLfile.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE_HGLfile.c.o: $(ARBHOME)/INCLUDE/awt.hxx
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o:  
GDE_HGLfile.c.o: 
GDE_HGLfile.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE_HGLfile.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
GDE_HGLfile.c.o: GDE_def.h GDE_extglob.h GDE_menu.h gde.hxx
GDE_ParseMenu.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE_ParseMenu.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE_ParseMenu.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE_ParseMenu.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE_ParseMenu.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE_ParseMenu.c.o: $(ARBHOME)/INCLUDE/awt.hxx
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o:  
GDE_ParseMenu.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE_ParseMenu.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
GDE_ParseMenu.c.o: GDE_def.h GDE_extglob.h GDE_global.h GDE_menu.h gde.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/awt.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
GDE_arbdb_io.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o:  
GDE_arbdb_io.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE_arbdb_io.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
GDE_arbdb_io.c.o: GDE_def.h GDE_extglob.h GDE_menu.h gde.hxx
GDE_event.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
GDE_event.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
GDE_event.c.o: $(ARBHOME)/INCLUDE/arbdb.h
GDE_event.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
GDE_event.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
GDE_event.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
GDE_event.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
GDE_event.c.o: $(ARBHOME)/INCLUDE/awt.hxx
GDE_event.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
GDE_event.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o:  
GDE_event.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
GDE_event.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
GDE_event.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
GDE_event.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
GDE_event.c.o: GDE_def.h GDE_extglob.h GDE_menu.h gde.hxx
