# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx

CPP_OBJECTS =  PH_data.o PH_root.o PH_main.o PH_filt.o PH_display.o PH_matr.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben


# DO NOT DELETE THIS LINE -- make depend depends on it.


PH_data.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PH_data.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PH_data.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PH_data.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PH_data.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PH_data.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:   
PH_data.c.o:   
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o:  
PH_data.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
PH_data.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PH_data.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PH_data.c.o: include.hxx phwin.hxx phylo.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PH_display.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PH_display.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PH_display.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PH_display.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PH_display.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o:  
PH_display.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
PH_display.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PH_display.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PH_display.c.o: PH_display.hxx include.hxx phwin.hxx phylo.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PH_filt.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PH_filt.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PH_filt.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PH_filt.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PH_filt.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:   
PH_filt.c.o:   
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o:  
PH_filt.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
PH_filt.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PH_filt.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PH_filt.c.o: include.hxx phwin.hxx phylo.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PH_main.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PH_main.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PH_main.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PH_main.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PH_main.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:   
PH_main.c.o:   
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o:  
PH_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
PH_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PH_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PH_main.c.o: PH_display.hxx include.hxx phwin.hxx phylo.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PH_matr.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PH_matr.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PH_matr.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PH_matr.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PH_matr.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:   
PH_matr.c.o:   
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o:  
PH_matr.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
PH_matr.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PH_matr.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PH_matr.c.o: include.hxx phwin.hxx phylo.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
PH_root.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
PH_root.c.o: $(ARBHOME)/INCLUDE/arbdb.h
PH_root.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
PH_root.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/awt.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/awt_nds.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/awt_seq_dna.hxx
PH_root.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:   
PH_root.c.o:   
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o:  
PH_root.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
PH_root.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
PH_root.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
PH_root.c.o: include.hxx phwin.hxx phylo.hxx
