# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c .cxx

include AD_MOBJECTS.h


OBJECTS = $(GB_O) $(GB_T) $(GB_PP)

$(MAIN): $(OBJECTS)
	$(AR) $(MAIN) $(OBJECTS)
.c.o:
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
.cxx.o:
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) *.c *.cxx
links:
	ln -s ../ARBDB/*.[ch] .

# DO NOT DELETE THIS LINE -- make depend depends on it.

adReference.o: 
adReference.o:  arbdb.h ad_prot.h
adReference.o: adlocal.h adtune.h adlmacros.h 
adReference.o:  
adTest.o: 
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  adlocal.h adtune.h adlmacros.h admap.h
ad_core.o: 
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  adlocal.h adtune.h adlmacros.h
ad_load.o: 
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  adlocal.h adtune.h adlmacros.h
ad_load.o: admap.h
ad_save_load.o: 
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o: adlocal.h adtune.h adlmacros.h admap.h
adcomm.o: 
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  adlocal.h adtune.h adlmacros.h
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o: 
adcompr.o: 
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:   adlocal.h adtune.h
adcompr.o: adlmacros.h arbdbt.h ad_t_prot.h ad_t_lpro.h
adhash.o: 
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:   adlocal.h adtune.h
adhash.o: adlmacros.h
adindex.o: 
adindex.o:  
adindex.o:  
adindex.o:  adlocal.h adtune.h adlmacros.h adlundo.h
adlang1.o: 
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:   adlocal.h adtune.h
adlang1.o: adlmacros.h arbdbt.h ad_t_prot.h ad_t_lpro.h
adlink.o: 
adlink.o:  
adlink.o:  
adlink.o: adlocal.h adtune.h adlmacros.h arbdb.h ad_prot.h
admalloc.o: 
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:   adlocal.h adtune.h
admalloc.o: adlmacros.h
admap.o: 
admap.o:  
admap.o:  
admap.o: adlocal.h adtune.h adlmacros.h admap.h
admath.o: 
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:   adlocal.h adtune.h
admath.o: adlmacros.h
adoptimize.o: 
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  adlocal.h adtune.h adlmacros.h
adperl.o:  
adperl.o:  
adperl.o:  arbdb.h ad_prot.h
adquery.o: 
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:   adlocal.h adtune.h
adquery.o: adlmacros.h
adseqcompr.o: 
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  adlocal.h adtune.h adlmacros.h arbdb.h
adseqcompr.o: ad_prot.h arbdbt.h ad_t_prot.h ad_t_lpro.h adseqcompr.h
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:   
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  adlocal.h adtune.h adlmacros.h
adsocket.o: 
adsort.o: 
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  arbdb.h ad_prot.h arbdbt.h ad_t_prot.h
adsort.o: ad_t_lpro.h
adstring.o: 
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:   adlocal.h
adstring.o: adtune.h adlmacros.h arbdbt.h ad_t_prot.h ad_t_lpro.h
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o: 
adsystem.o: 
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  adlocal.h adtune.h adlmacros.h
adsystem.o: arbdbt.h ad_t_prot.h ad_t_lpro.h
adtables.o: 
adtables.o:  
adtables.o:  
adtables.o: adlocal.h adtune.h adlmacros.h arbdb.h ad_prot.h arbdbt.h
adtables.o: ad_t_prot.h ad_t_lpro.h
adtools.o: 
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:   
adtools.o:   adlocal.h adtune.h
adtools.o: adlmacros.h arbdb.h ad_prot.h arbdbt.h ad_t_prot.h ad_t_lpro.h
adtune.o: adtune.h
arbdb.o: 
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  adlocal.h adtune.h adlmacros.h arbdb.h
arbdb.o: ad_prot.h
arbdbpp.o:  arbdb.h ad_prot.h arbdbt.h
arbdbpp.o: ad_t_prot.h ad_t_lpro.h
