# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package ARB;
use base qw(Exporter);
use base qw(DynaLoader);
package ARBc;
bootstrap ARB;
package ARB;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package ARB;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package ARB;

*open = *ARBc::open;
*save = *ARBc::save;
*save_as = *ARBc::save_as;
*close = *ARBc::close;
*get_db_path = *ARBc::get_db_path;
*abort_transaction = *ARBc::abort_transaction;
*begin_transaction = *ARBc::begin_transaction;
*commit_transaction = *ARBc::commit_transaction;
*write_flag = *ARBc::write_flag;
*read_flag = *ARBc::read_flag;
*check_key = *ARBc::check_key;
*search = *ARBc::search;
*await_error = *ARBc::await_error;
*checksum = *ARBc::checksum;
*read_string = *ARBc::read_string;
*read_as_string = *ARBc::read_as_string;
*read_name = *ARBc::read_name;
*write_int = *ARBc::write_int;
*write_string = *ARBc::write_string;
*remote_action = *ARBc::remote_action;
*remote_awar = *ARBc::remote_awar;
*remote_read_awar = *ARBc::remote_read_awar;
*first_species = *ARBc::first_species;
*next_species = *ARBc::next_species;
*first_marked_species = *ARBc::first_marked_species;
*next_marked_species = *ARBc::next_marked_species;
*GBT_get_default_alignment = *ARBc::GBT_get_default_alignment;
*message = *ARBc::message;

# ------- VARIABLE STUBS --------

package ARB;

1;
