/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef ARB_MATCH_H
#define ARB_MATCH_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* arb_match.cxx */

#ifndef ARB_CORE_H
#include "arb_core.h"
#endif

GBS_regex *GBS_compile_regexpr(const char *regexpr, GB_CASE case_flag, GB_ERROR *error);
void GBS_free_regexpr(GBS_regex *toFree);
const char *GBS_unwrap_regexpr(const char *regexpr_in_slashes, GB_CASE *case_flag, GB_ERROR *error);
const char *GBS_regmatch_compiled(const char *str, GBS_regex *comreg, size_t *matchlen);
const char *GBS_regmatch(const char *str, const char *regExpr, size_t *matchlen, GB_ERROR *error);
char *GBS_regreplace(const char *str, const char *regReplExpr, GB_ERROR *error);

#else
#error arb_match.h included twice
#endif /* ARB_MATCH_H */
