/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef NT_CB_H
#define NT_CB_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* NT_cb.cxx */

#ifndef ARBDB_BASE_H
#include <arbdb_base.h>
#endif
#ifndef AW_BASE_HXX
#include <aw_base.hxx>
#endif
class AWT_canvas;

void NT_delete_mark_all_cb(void *, AWT_canvas *ntw);
AW_window *NT_create_select_tree_window(AW_root *awr, const char *awar_tree);
void NT_select_bottom_tree(AW_window *aww, const char *awar_tree);
AW_window *NT_create_select_alignment_window(AW_root *awr);
void NT_system_cb(AW_window *aww, AW_CL cl_command, AW_CL cl_auto_help_file);
void NT_system_in_xterm_cb(AW_window *aww, AW_CL cl_command, AW_CL cl_auto_help_file);

/* NT_extern.cxx */
bool nt_disconnect_from_db(AW_root *aw_root, GBDATA*& gb_main_ref);
void nt_start(const char *arb_ntree_args, bool restart_with_new_ARB_PID);
void nt_exit(AW_window *aws, AW_CL exitcode);
void nt_restart(AW_root *aw_root, const char *arb_ntree_args);
GBT_TREE *nt_get_tree_root_of_canvas(AWT_canvas *ntw);
int NT_get_canvas_id(AWT_canvas *ntw);
void nt_create_main_window(AW_root *aw_root);

#else
#error NT_cb.h included twice
#endif /* NT_CB_H */
