# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx

CPP_OBJECTS = ED4_nds.o ED4_secedit.o \
	 	ED4_main.o ED4_mini_classes.o ED4_edit_string.o ED4_base.o ED4_manager.o ED4_terminal.o \
	 	ED4_root.o EDB_root_bact.o ED4_window.o ED4_members.o ED4_no_class.o ED4_list.o ED4_text_terminals.o \
		ED4_cursor.o ED4_tools.o ED4_search.o ED4_block.o edit_naligner.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c -o $@ $(@:.o=.cxx)  $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)


# DO NOT DELETE THIS LINE -- make depend depends on it.

ED4_nds.o: 
ED4_nds.o:  
ED4_nds.o:  
ED4_nds.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_nds.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_nds.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_nds.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_nds.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_nds.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_nds.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_nds.o: $(ARBHOME)/INCLUDE/aw_device.hxx ed4_class.hxx
ED4_nds.o: ed4_defs.hxx ed4_search.hxx ed4_awars.hxx
ED4_secedit.o: 
ED4_secedit.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_secedit.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_secedit.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_secedit.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
ED4_secedit.o: $(ARBHOME)/INCLUDE/secedit.hxx
ED4_secedit.o: 
ED4_secedit.o:  
ED4_secedit.o: $(ARBHOME)/INCLUDE/sec_graphic.hxx
ED4_secedit.o:  
ED4_secedit.o:  
ED4_secedit.o: ed4_secedit.hxx
ED4_main.o: 
ED4_main.o:  
ED4_main.o:  
ED4_main.o:  
ED4_main.o:  
ED4_main.o:  
ED4_main.o:  
ED4_main.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_main.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_main.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_main.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_main.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/awt_seq_colors.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/awt_map_key.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/awt.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/st_window.hxx
ED4_main.o: $(ARBHOME)/INCLUDE/gde.hxx ed4_class.hxx ed4_defs.hxx
ED4_main.o: ed4_search.hxx ed4_awars.hxx ed4_edit_string.hxx ed4_nds.hxx
ED4_main.o: edit_naligner.hxx
ED4_mini_classes.o: 
ED4_mini_classes.o:  
ED4_mini_classes.o:  
ED4_mini_classes.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_mini_classes.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_mini_classes.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_mini_classes.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_mini_classes.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_mini_classes.o: $(ARBHOME)/INCLUDE/awt_iupac.hxx ed4_class.hxx
ED4_mini_classes.o: ed4_defs.hxx ed4_search.hxx ed4_edit_string.hxx
ED4_mini_classes.o: ed4_awars.hxx ed4_tools.hxx
ED4_edit_string.o: 
ED4_edit_string.o: 
ED4_edit_string.o:  
ED4_edit_string.o: 
ED4_edit_string.o: 
ED4_edit_string.o:  
ED4_edit_string.o:  
ED4_edit_string.o:  
ED4_edit_string.o:  
ED4_edit_string.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_edit_string.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_edit_string.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_edit_string.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_edit_string.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_edit_string.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_edit_string.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_edit_string.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_edit_string.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
ED4_edit_string.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx
ED4_edit_string.o: $(ARBHOME)/INCLUDE/awt_map_key.hxx ed4_defs.hxx
ED4_edit_string.o: ed4_edit_string.hxx ed4_class.hxx ed4_search.hxx
ED4_edit_string.o: ed4_awars.hxx
ED4_base.o: 
ED4_base.o:  
ED4_base.o:  
ED4_base.o:  
ED4_base.o:  
ED4_base.o:  
ED4_base.o:  
ED4_base.o:  $(ARBHOME)/INCLUDE/arbdb.h
ED4_base.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_base.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_base.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_base.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_base.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_base.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_base.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_base.o: $(ARBHOME)/INCLUDE/aw_preset.hxx ed4_class.hxx
ED4_base.o: ed4_defs.hxx ed4_search.hxx ed4_awars.hxx ed4_edit_string.hxx
ED4_manager.o: 
ED4_manager.o:  
ED4_manager.o:  
ED4_manager.o:  
ED4_manager.o:  
ED4_manager.o:  
ED4_manager.o:  
ED4_manager.o:  $(ARBHOME)/INCLUDE/arbdb.h
ED4_manager.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_manager.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_manager.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_manager.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_manager.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_manager.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_manager.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_manager.o: $(ARBHOME)/INCLUDE/aw_preset.hxx ed4_class.hxx
ED4_manager.o: ed4_defs.hxx ed4_search.hxx ed4_awars.hxx ed4_edit_string.hxx
ED4_manager.o: ed4_tools.hxx
ED4_terminal.o: 
ED4_terminal.o:  
ED4_terminal.o:  
ED4_terminal.o:  
ED4_terminal.o:  
ED4_terminal.o:  
ED4_terminal.o:  
ED4_terminal.o:  $(ARBHOME)/INCLUDE/arbdb.h
ED4_terminal.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_terminal.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_terminal.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_terminal.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_terminal.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_terminal.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_terminal.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_terminal.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
ED4_terminal.o: $(ARBHOME)/INCLUDE/awt_seq_colors.hxx
ED4_terminal.o: $(ARBHOME)/INCLUDE/st_window.hxx ed4_class.hxx
ED4_terminal.o: ed4_defs.hxx ed4_search.hxx ed4_awars.hxx ed4_edit_string.hxx
ED4_terminal.o: ed4_block.hxx ed4_nds.hxx
ED4_root.o:  
ED4_root.o:  
ED4_root.o:  
ED4_root.o:  
ED4_root.o:  
ED4_root.o:  
ED4_root.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_root.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_root.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_root.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_root.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/awt.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/awt_seq_colors.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/awt_map_key.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/awtc_constructSequence.hxx
ED4_root.o: ../NTREE/nt_date.h $(ARBHOME)/INCLUDE/BI_helix.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/st_window.hxx
ED4_root.o: $(ARBHOME)/INCLUDE/gde.hxx ed4_class.hxx ed4_defs.hxx
ED4_root.o: ed4_search.hxx ed4_awars.hxx ed4_tools.hxx ed4_block.hxx
ED4_root.o: ed4_nds.hxx ed4_secedit.hxx edit_naligner.hxx
EDB_root_bact.o: 
EDB_root_bact.o:  
EDB_root_bact.o:  
EDB_root_bact.o: $(ARBHOME)/INCLUDE/arbdb.h
EDB_root_bact.o: $(ARBHOME)/INCLUDE/ad_prot.h
EDB_root_bact.o: $(ARBHOME)/INCLUDE/arbdbt.h
EDB_root_bact.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
EDB_root_bact.o: $(ARBHOME)/INCLUDE/aw_root.hxx
EDB_root_bact.o: $(ARBHOME)/INCLUDE/aw_window.hxx
EDB_root_bact.o: $(ARBHOME)/INCLUDE/aw_device.hxx ed4_class.hxx
EDB_root_bact.o: ed4_defs.hxx ed4_search.hxx
ED4_window.o:  
ED4_window.o:  
ED4_window.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_window.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_window.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_window.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_window.o: $(ARBHOME)/INCLUDE/aw_device.hxx ed4_class.hxx
ED4_window.o: ed4_defs.hxx ed4_search.hxx ed4_tools.hxx
ED4_members.o: 
ED4_members.o:  
ED4_members.o:  
ED4_members.o:  
ED4_members.o:  
ED4_members.o:  
ED4_members.o:  $(ARBHOME)/INCLUDE/arbdb.h
ED4_members.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_members.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_members.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_members.o: $(ARBHOME)/INCLUDE/aw_device.hxx ed4_class.hxx
ED4_members.o: ed4_defs.hxx ed4_search.hxx
ED4_no_class.o: 
ED4_no_class.o:  
ED4_no_class.o:  
ED4_no_class.o:  
ED4_no_class.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_no_class.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_no_class.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_no_class.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_no_class.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/awt_seq_colors.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/awt.hxx
ED4_no_class.o: $(ARBHOME)/INCLUDE/st_window.hxx ed4_awars.hxx
ED4_no_class.o: ed4_class.hxx ed4_defs.hxx ed4_search.hxx ed4_edit_string.hxx
ED4_no_class.o: ed4_tools.hxx ed4_nds.hxx
ED4_list.o: 
ED4_list.o: 
ED4_list.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_list.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_list.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_list.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_list.o: $(ARBHOME)/INCLUDE/aw_device.hxx ed4_class.hxx
ED4_list.o: ed4_defs.hxx ed4_search.hxx 
ED4_list.o:  
ED4_text_terminals.o: 
ED4_text_terminals.o: 
ED4_text_terminals.o:  
ED4_text_terminals.o:  
ED4_text_terminals.o:  
ED4_text_terminals.o:  
ED4_text_terminals.o:  
ED4_text_terminals.o: 
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/awt_seq_colors.hxx
ED4_text_terminals.o: $(ARBHOME)/INCLUDE/st_window.hxx
ED4_text_terminals.o: ed4_class.hxx ed4_defs.hxx ed4_search.hxx ed4_awars.hxx
ED4_text_terminals.o: ed4_edit_string.hxx ed4_block.hxx ed4_nds.hxx
ED4_cursor.o: 
ED4_cursor.o:  
ED4_cursor.o:  
ED4_cursor.o:  
ED4_cursor.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_cursor.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_cursor.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_cursor.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_cursor.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_cursor.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_cursor.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_cursor.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_cursor.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_cursor.o: $(ARBHOME)/INCLUDE/BI_helix.hxx ed4_class.hxx
ED4_cursor.o: ed4_defs.hxx ed4_search.hxx ed4_edit_string.hxx ed4_tools.hxx
ED4_cursor.o: ed4_awars.hxx ed4_secedit.hxx
ED4_tools.o: 
ED4_tools.o:  
ED4_tools.o:  
ED4_tools.o:  $(ARBHOME)/INCLUDE/arbdb.h
ED4_tools.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_tools.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_tools.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_tools.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_tools.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_tools.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_tools.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_tools.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
ED4_tools.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx
ED4_tools.o: $(ARBHOME)/INCLUDE/awt_iupac.hxx ed4_class.hxx
ED4_tools.o: ed4_defs.hxx ed4_search.hxx ed4_edit_string.hxx ed4_tools.hxx
ED4_tools.o: ed4_awars.hxx
ED4_search.o: 
ED4_search.o:  
ED4_search.o:  
ED4_search.o:   
ED4_search.o:  $(ARBHOME)/INCLUDE/arbdb.h
ED4_search.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_search.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_search.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_search.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_search.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_search.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_search.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_search.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_search.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx
ED4_search.o: $(ARBHOME)/INCLUDE/awt.hxx ed4_awars.hxx
ED4_search.o: ed4_class.hxx ed4_defs.hxx ed4_search.hxx ed4_tools.hxx
ED4_block.o: 
ED4_block.o:  
ED4_block.o:  
ED4_block.o:  
ED4_block.o: $(ARBHOME)/INCLUDE/arbdb.h
ED4_block.o: $(ARBHOME)/INCLUDE/ad_prot.h
ED4_block.o: $(ARBHOME)/INCLUDE/arbdbt.h
ED4_block.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ED4_block.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ED4_block.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ED4_block.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ED4_block.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ED4_block.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ED4_block.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx ed4_awars.hxx
ED4_block.o: ed4_class.hxx ed4_defs.hxx ed4_search.hxx ed4_tools.hxx
ED4_block.o: ed4_block.hxx ed4_edit_string.hxx
edit_naligner.o: 
edit_naligner.o: 
edit_naligner.o: $(ARBHOME)/INCLUDE/arbdb.h
edit_naligner.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit_naligner.o: $(ARBHOME)/INCLUDE/arbdbt.h
edit_naligner.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
edit_naligner.o: 
edit_naligner.o:  
edit_naligner.o: 
