.SUFFIXES: .o .c .cxx

OBJECT =  CAP2.o Restriction.o Zuk_to_gen.o count.o findall.o lsadt.o \
	sho_helix.o varpos.o


all: $(OBJECT:%.o=../../bin/%)

../../bin/%: %.c
	$(ACC) $(cflags) -o $@ $< $(AINCLUDES) $(LIB) -lm

depend:
	makedepend -o '' -p ../../bin/ $(MAKEDEPENDINC) $(OBJECT:.o=.c*)

# DO NOT DELETE THIS LINE -- make depend depends on it.


CAP2:  
CAP2:  
CAP2:  
CAP2:   
CAP2: 
CAP2: 
CAP2: 
Restriction:  
Restriction:  
Restriction:  
Restriction:  
Restriction:  
Restriction: 
Restriction: 
Restriction:  Flatio.c
Zuk_to_gen:  
Zuk_to_gen:  
Zuk_to_gen:  
Zuk_to_gen:   
Zuk_to_gen: 
Zuk_to_gen: 
Zuk_to_gen: 
count:  
count:  
count:  
count:  
count:  
count:   
count:   
count: 
count: 
count:  Flatio.c
findall:  
findall:  
findall:  
findall:   
findall:  
findall: 
findall:  Flatio.c
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:   
lsadt:   
lsadt:   
lsadt:   
lsadt:  
lsadt:  
lsadt:   
lsadt: 
lsadt: 
lsadt: 
lsadt: 
lsadt: 
lsadt: 
sho_helix:  
sho_helix:  
sho_helix:  
sho_helix:   
sho_helix:  
sho_helix: 
sho_helix:  Flatio.c
varpos:  
varpos:  
varpos:  
varpos:   
varpos:  
varpos: 
varpos:  Flatio.c
