.SUFFIXES: .o .c .cxx

OBJECT =  CAP2.o Restriction.o Zuk_to_gen.o count.o findall.o lsadt.o \
	sho_helix.o varpos.o


all: $(OBJECT:%.o=../../bin/%)

../../bin/%: %.c
	$(ACC) $(cflags) -o $@ $< $(AINCLUDES) $(LIB) -lm

depend:
	makedepend -o '' -p ../../bin/ $(MAKEDEPENDINC) $(OBJECT:.o=.c*)

# DO NOT DELETE THIS LINE -- make depend depends on it.

../../bin/CAP2:  
../../bin/CAP2:  
../../bin/CAP2: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/CAP2:  
../../bin/CAP2:  
../../bin/CAP2:  
../../bin/CAP2: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/CAP2: 
../../bin/Restriction: Flatio.c  
../../bin/Restriction:  
../../bin/Restriction: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/Restriction:  
../../bin/Restriction:  
../../bin/Restriction:  
../../bin/Restriction: 
../../bin/Restriction: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/Restriction: 
../../bin/Zuk_to_gen:  
../../bin/Zuk_to_gen:  
../../bin/Zuk_to_gen: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/Zuk_to_gen:  
../../bin/Zuk_to_gen:  
../../bin/Zuk_to_gen:  
../../bin/Zuk_to_gen: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/Zuk_to_gen: 
../../bin/count:  
../../bin/count:  
../../bin/count:  
../../bin/count:  Flatio.c 
../../bin/count: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/count:  
../../bin/count:  
../../bin/count:  
../../bin/count: 
../../bin/count: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/count: 
../../bin/findall: Flatio.c  
../../bin/findall:  
../../bin/findall: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/findall:  
../../bin/findall:  
../../bin/findall:  
../../bin/findall: 
../../bin/findall: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/findall: 
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt: 
../../bin/lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h
../../bin/lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/float.h
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt:  
../../bin/lsadt: 
../../bin/sho_helix: Flatio.c  
../../bin/sho_helix:  
../../bin/sho_helix: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/sho_helix:  
../../bin/sho_helix:  
../../bin/sho_helix:  
../../bin/sho_helix: 
../../bin/sho_helix: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/sho_helix: 
../../bin/varpos: Flatio.c  
../../bin/varpos:  
../../bin/varpos: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
../../bin/varpos:  
../../bin/varpos:  
../../bin/varpos:  
../../bin/varpos: 
../../bin/varpos: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
../../bin/varpos: 
