# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c .cxx
CPP_OBJECTS = adtsequence.o adt_edit.o adtali.o adextended.o adseq.o adspecies.o admain.o adali.o  liste.o 
$(MAIN): $(CPP_OBJECTS)
	$(ARLIB) $(@:.a=).$(SHARED_LIB_SUFFIX) $(CPP_OBJECTS)
	touch $@
.cxx.o: 
	$(CCPLIB) $(cflags) -c $< $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

adtsequence.o:  
adtsequence.o:  
adtsequence.o:  
adtsequence.o:  
adtsequence.o:  
adtsequence.o: 
adtsequence.o: $(ARBHOME)/INCLUDE/arbdb.h
adtsequence.o: $(ARBHOME)/INCLUDE/ad_prot.h arbdb++.hxx
adtsequence.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx adtools.hxx
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:  
adt_edit.o:   
adt_edit.o: $(ARBHOME)/INCLUDE/arbdb.h
adt_edit.o: $(ARBHOME)/INCLUDE/ad_prot.h arbdb++.hxx
adt_edit.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx adtools.hxx
adtali.o:  
adtali.o:  
adtali.o:  
adtali.o:  
adtali.o:   
adtali.o:  
adtali.o:  
adtali.o:  
adtali.o:  
adtali.o: $(ARBHOME)/INCLUDE/arbdb.h
adtali.o: $(ARBHOME)/INCLUDE/ad_prot.h adtools.hxx arbdb++.hxx
adtali.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adextended.o:  
adextended.o:  
adextended.o:  
adextended.o:  
adextended.o:  
adextended.o: $(ARBHOME)/INCLUDE/arbdb.h
adextended.o: $(ARBHOME)/INCLUDE/ad_prot.h
adextended.o: $(ARBHOME)/INCLUDE/arbdbt.h
adextended.o: $(ARBHOME)/INCLUDE/ad_t_prot.h arbdb++.hxx
adextended.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adseq.o:  
adseq.o:  
adseq.o:  
adseq.o:  
adseq.o:   
adseq.o:  
adseq.o:  
adseq.o:  
adseq.o:   
adseq.o:  
adseq.o: $(ARBHOME)/INCLUDE/arbdb.h
adseq.o: $(ARBHOME)/INCLUDE/ad_prot.h
adseq.o: $(ARBHOME)/INCLUDE/arbdbt.h
adseq.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
adseq.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx arbdb++.hxx
adspecies.o:  
adspecies.o:  
adspecies.o:  
adspecies.o:  
adspecies.o:  
adspecies.o: $(ARBHOME)/INCLUDE/arbdb.h
adspecies.o: $(ARBHOME)/INCLUDE/ad_prot.h
adspecies.o: $(ARBHOME)/INCLUDE/arbdbt.h
adspecies.o: $(ARBHOME)/INCLUDE/ad_t_prot.h arbdb++.hxx
adspecies.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
admain.o:  
admain.o:  
admain.o:  
admain.o:  
admain.o:  
admain.o: $(ARBHOME)/INCLUDE/arbdb.h
admain.o: $(ARBHOME)/INCLUDE/ad_prot.h
admain.o: $(ARBHOME)/INCLUDE/arbdbt.h
admain.o: $(ARBHOME)/INCLUDE/ad_t_prot.h arbdb++.hxx
admain.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adali.o:  
adali.o:  
adali.o:  
adali.o:  
adali.o:  
adali.o: $(ARBHOME)/INCLUDE/arbdb.h
adali.o: $(ARBHOME)/INCLUDE/ad_prot.h
adali.o: $(ARBHOME)/INCLUDE/arbdbt.h
adali.o: $(ARBHOME)/INCLUDE/ad_t_prot.h arbdb++.hxx
adali.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
liste.o:  
liste.o:  
liste.o:  
liste.o:  
liste.o: $(ARBHOME)/INCLUDE/arbdb.h
liste.o: $(ARBHOME)/INCLUDE/ad_prot.h arbdb++.hxx
liste.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
