# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx


CPP_OBJECTS =  SEER_main.o SEER_interface.o SEER_connect.o SEER_arb.o SEER_to_seer.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)



.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


SEER_arb.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_arb.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_arb.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_arb.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_arb.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEER_arb.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEER_arb.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_arb.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEER_arb.c.o: $(ARBHOME)/INCLUDE/awt.hxx
SEER_arb.c.o: $(ARBHOME)/INCLUDE/ntree.hxx
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o:   
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o:  
SEER_arb.c.o: 
SEER_arb.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
SEER_arb.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
SEER_arb.c.o: seer.hxx seer_interface.hxx
SEER_connect.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_connect.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_connect.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_connect.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_connect.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o: 
SEER_connect.c.o: 
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o:  
SEER_connect.c.o: 
SEER_connect.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
SEER_connect.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
SEER_connect.c.o: seer.hxx seer_interface.hxx
SEER_interface.c.o:  
SEER_interface.c.o: 
SEER_interface.c.o: 
SEER_interface.c.o: 
SEER_interface.c.o:  
SEER_interface.c.o:  
SEER_interface.c.o:  
SEER_interface.c.o:  
SEER_interface.c.o:  
SEER_interface.c.o:  
SEER_interface.c.o:  
SEER_interface.c.o: 
SEER_interface.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
SEER_interface.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
SEER_interface.c.o: seer_interface.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_main.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_main.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_main.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_main.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/awt.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/awt_dtree.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
SEER_main.c.o: $(ARBHOME)/INCLUDE/ntree.hxx
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:   
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o:  
SEER_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
SEER_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
SEER_main.c.o: seer.hxx seer_interface.hxx
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/awt.hxx
SEER_to_seer.c.o: $(ARBHOME)/INCLUDE/ntree.hxx
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o:  
SEER_to_seer.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
SEER_to_seer.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
SEER_to_seer.c.o: seer.hxx seer_interface.hxx
