#!/bin/bash -x
# usage: arb_bootstrap count treeprog [keyin4treeprog]
# 'count'            is the number of generated trees
# 'treeprog'         calculates the trees (e.g. dnapars, protpars)
# 'keyin4treeprog'   is echoed to stdin of 'treeprog'
# expects input data in "infile"

COUNT=$1
TREEPROG=$2
KEYIN=$3
RANDOMSEED=$(($RANDOM|1)) # a odd number

echo "-consense $COUNT" >arb_read_tree_args

arb_echo $RANDOMSEED r $COUNT y | seqboot

if [ \! -f outfile ] ; then
    echo "Error in seqboot: 'outfile' not generated"
else
    mv -f outfile infile
    if [ -z "$KEYIN" ]; then
        $TREEPROG
    else
        arb_echo $KEYIN | $TREEPROG
    fi

    if [ \! -f treefile ] ; then
        echo "Error running $TREEPROG: 'treefile' not generated"
    else
        if [ \! -s treefile ] ; then
            echo "Error running $TREEPROG: 'treefile' is empty"
            rm treefile
        else
            mv -f treefile infile
            arb_echo y | consense

            if [ \! -f treefile ] ; then
                echo "Error running consense: 'treefile' not generated"
            else
                if [ \! -f outfile ] ; then
                    echo "Warning running consense: 'outfile' not generated"
                else
                    if [ \! -s outfile ] ; then
                        echo "Warning running consense: 'outfile' is empty"
                    else
                        arb_textedit outfile &
                    fi
                fi
            fi
        fi
    fi
fi
