#!/bin/bash -x

if [ -z "$8" ]; then
    echo "Usage: arb_proml bootstrap aachangemodel viewreport analysis randomize rearrange rate_variation interactive"
else
    BOOTSTRAP=$1
    MODEL=$2
    REPORT=$3
    ANALYSIS=$4
    RANDOMIZE=$5
    REARRANGE=$6
    RATE_VARIATION=$7
    INTERACTIVE=$8

    FLAGS=""

    if [ "$MODEL" = "PAM" ]; then
        FLAGS="$FLAGS p"
    fi
    if [ "$ANALYSIS" = "fine" ]; then
        FLAGS="$FLAGS s"
    fi
    if [ "$RANDOMIZE" = "1" ]; then
        RANDOMSEED=$(($RANDOM|1)) # a odd number
        FLAGS="$FLAGS j $RANDOMSEED 1"
    fi
    if [ "$REARRANGE" = "1" ]; then
        FLAGS="$FLAGS g"
    fi

    case $RATE_VARIATION in
        0) ;;
        1) FLAGS="$FLAGS r" ;;
        2) FLAGS="$FLAGS r r" ;;
        *)  echo "Illegal value for 'rate_variation'"; exit 1 ;;
    esac

    if [ "$BOOTSTRAP" = "0" ]; then
        if [ "$INTERACTIVE" = "0" ]; then
            arb_echo $FLAGS y | proml
        else
            (arb_echo $FLAGS ; cat - ) | ( proml ; echo "Press RETURN to continue.." )
        fi
        #proml
        echo >arb_read_tree_args
        WHAT=proml
    else
        arb_bootstrap $BOOTSTRAP proml $FLAGS
        WHAT=arb_bootstrap/proml/consense
    fi

    if [ -f outfile ]; then
        if [ -s outfile ]; then
            if [ "$REPORT" = "1" ]; then
                arb_textedit outfile &
            fi
        else
            echo "$WHAT: Warning: generated 'outfile' is empty"
        fi
    else
        echo "$WHAT: Warning: 'outfile' was not created"
    fi
fi
