/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef ARB_SIGNAL_H
#define ARB_SIGNAL_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* arb_signal.cxx */

#ifndef ARB_CORE_H
#include <arb_core.h>
#endif

void GBK_install_SIGSEGV_handler(bool dump_backtrace);
GB_ERROR GBK_test_address(long *address, long key);
bool GBK_running_on_valgrind(void);
bool GBK_raises_SIGSEGV(void (*cb)(void));

#else
#error arb_signal.h included twice
#endif /* ARB_SIGNAL_H */
