/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef ARB_MISC_H
#define ARB_MISC_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* arb_misc.cxx */

#ifndef _GLIBCXX_CSTDLIB
#include <cstdlib>
#endif

const char *GBS_readable_size(unsigned long long size, const char *unit_suffix);
const char *GBS_readable_timediff(size_t seconds);

#else
#error arb_misc.h included twice
#endif /* ARB_MISC_H */
