/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef ARB_STRING_H
#define ARB_STRING_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* arb_string.cxx */
char *GB_strduplen(const char *p, unsigned len);
char *GB_strpartdup(const char *start, const char *end);
char *GB_strndup(const char *start, int len);
const char *GB_date_string(void);
const char *GB_dateTime_suffix(void);
const char *GB_keep_string(char *str);

#else
#error arb_string.h included twice
#endif /* ARB_STRING_H */
