.SUFFIXES: .o .c

OBJECTS = main.o Window.o menu.o ReadData.o Draw.o WriteData.o


$(ARBHOME)/bin/LoopTool: $(OBJECTS)
	$(ACC) -o $@ $(OBJECTS) -L$(OPENWINHOME)/lib -L$(XHOME)/lib -lm  -lxview  -lolgx -lX11

.c.o:
	$(ACC) -c $(cflags) $(AINCLUDES) -I$(OPENWINHOME)/include $<

depend:
	makedepend $(MAKEDEPENDINC) $(OBJECTS:.o=.c)
# DO NOT DELETE THIS LINE -- make depend depends on it.

main.o:  
main.o:  
main.o: 
main.o: 
main.o: 
main.o:  loop.h globals.h
Window.o:  
Window.o: 
Window.o: 
Window.o: 
Window.o: 
Window.o: 
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:   loop.h globals.h
Window.o: 
menu.o: 
menu.o: 
menu.o: 
menu.o: 
menu.o:  loop.h globals.h
ReadData.o: 
ReadData.o: 
ReadData.o:  
ReadData.o:  
ReadData.o:  
ReadData.o:  
ReadData.o:  
ReadData.o:  loop.h globals.h
Draw.o: 
Draw.o: 
Draw.o: 
Draw.o: 
Draw.o:  
Draw.o:  
Draw.o:  
Draw.o:  
Draw.o:  
Draw.o:  loop.h globals.h
WriteData.o: 
WriteData.o: 
WriteData.o:  
WriteData.o:  
WriteData.o:  
WriteData.o:  
WriteData.o:  
WriteData.o:  loop.h globals.h
