#!/bin/sh
tmp=/tmp/arb_fdnaml_${USER}_$$
mv infile $tmp
nice -19 fastdnaml < $tmp &
sig=$!
/bin/echo "$sig $$ \c" >>/tmp/arb_pids_${USER}_${ARB_PID}
wait
rm -f $tmp
rm -f checkpoint.$sig
mv treefile.$sig treefile
