#!/bin/sh

echo '***********************************************'
echo 'Hallo Leute, auf welchem Rechner moechten Sie ARB starten'
echo ''
echo 'soul:	Nur spaet nachmittags und abends verwenden, dieser Rechner'
echo '	ist eigentlich fuer unsere Informatiker reserviert.'
echo
echo 'blues: (Zur Zeit abgeschaltet!)'
echo ''
echo 'boarisch: Ein schneller Linux PC, langsamer als blues aber schneller als soul'
echo ''
echo 'disco: Ein schneller Solaris-Rechner (erste Wahl!)'
echo ''
echo 'Geben Sie bitte den Rechner-Namen ein:'
read a
pwd=`pwd`
xon $a "xterm -sb -sl 2000 -e sh -c \"cd $pwd;pwd; arb;echo press ctrl-c to close log window;sleep 300000\""
