#!/bin/sh
#watch out for DEPOT and DEPOT2 [they are no longer in use]
name=`date '+arbsrc_%Y_%m_%d__%H_%M.tgz'`

util/arb_srclst.pl | sort > arbsrc.lst

# util/arb_srclst    | sort > arbsrc_old.lst
# echo '< = no longer saved'
# echo '> = wasnt saved before'
# diff arbsrc_old.lst arbsrc_new.lst

tar -zcf $name --files-from=arbsrc.lst

rm -f arbsrc.tgz
ln -s $name arbsrc.tgz
ls -alG -rt arbsrc*

