#!/bin/sh
#watch out for DEPOT and DEPOT2 [they are no longer in use]
name=`date '+arbsrc_%Y_%m_%d__%H_%M.tgz'`

( ( util/arb_srclst.pl > arbsrc.lst.tmp ) || \
  ( echo "Failed to build arbsrc.lst" ; false ) \
) && \
sort < arbsrc.lst.tmp > arbsrc.lst && \
rm -f arbsrc.lst.tmp && \
tar -zcf $name --files-from=arbsrc.lst && \
( rm -f arbsrc.tgz ; \
  ln -s $name arbsrc.tgz ; \
  ls -alG -rt arbsrc* ; \ 
  true
)

