.SUFFIXES: .o .c

OBJECTS = main.o Window.o menu.o ReadData.o Draw.o WriteData.o


$(ARBHOME)/bin/LoopTool: $(OBJECTS)
	$(ACC) -o $@ $(OBJECTS) -L$(OPENWINHOME)/lib -L$(XHOME)/lib -lm  -lxview  -lolgx -lX11

.c.o:
	$(ACC) -c $(cflags) $(AINCLUDES) -I$(OPENWINHOME)/include $<

depend:
	makedepend $(MAKEDEPENDINC) $(OBJECTS:.o=.c)
# DO NOT DELETE THIS LINE -- make depend depends on it.


Draw.o:  
Draw.o:  
Draw.o:  
Draw.o:   
Draw.o:   
Draw.o: 
Draw.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
Draw.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h globals.h
Draw.o: loop.h
ReadData.o:  
ReadData.o:  
ReadData.o:  
ReadData.o:  
ReadData.o:   
ReadData.o:  
ReadData.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ReadData.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h globals.h
ReadData.o: loop.h
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:  
Window.o:   
Window.o:  
Window.o: 
Window.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
Window.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
Window.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h globals.h
Window.o: loop.h
WriteData.o:  
WriteData.o:  
WriteData.o:  
WriteData.o:  
WriteData.o:   
WriteData.o:  
WriteData.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
WriteData.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
WriteData.o: globals.h loop.h
main.o:  
main.o:  
main.o:  
main.o:   
main.o:   
main.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
main.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h globals.h
main.o: loop.h
menu.o:  
menu.o:  
menu.o:  
menu.o:   
menu.o: 
menu.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
menu.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h globals.h
menu.o: loop.h
