#!/bin/sh
TMPDIR=~/.arb_tmp/tmp
mkdir -p $TMPDIR
tmp=$TMPDIR/arb_fdnaml_$$
mv infile $tmp
nice -19 $1 < $tmp &
sig=$!
/bin/echo "$sig $$ \c" >> $TMPDIR/arb_pids_${USER}_${ARB_PID}
wait
# echo $tmp not deleted for debugging purposes
rm -f $tmp
rm -f checkpoint.$sig
mv treefile.$sig treefile
test -f treefile || (arb_message "Error: 'treefile' not generated (inspect console for details)";false)
