# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c .cxx

OBJECTS = AC_main.o AC_tree.o AC_sequence.o DEBUG_tools.o AC_toys_n_tools.o

$(MAIN): $(OBJECTS)
	$(AR) $(MAIN) $(OBJECTS)

AC_sequence.o: AC_sequence.cxx 
	CC -O $(cflags) -c $< $(CPPINCLUDES)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


AC_main.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_main.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AC_main.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AC_main.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o:   
AC_main.c.o:   
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o:  
AC_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AC_main.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ac.hxx
AC_sequence.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_sequence.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AC_sequence.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AC_sequence.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o:  
AC_sequence.c.o: 
AC_sequence.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AC_sequence.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AC_sequence.c.o: ac.hxx
AC_toys_n_tools.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_toys_n_tools.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AC_toys_n_tools.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AC_toys_n_tools.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o:  
AC_toys_n_tools.c.o: 
AC_toys_n_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AC_toys_n_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AC_toys_n_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AC_toys_n_tools.c.o: ac.hxx
AC_tree.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_tree.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AC_tree.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AC_tree.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:   
AC_tree.c.o:   
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o:  
AC_tree.c.o: 
AC_tree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AC_tree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AC_tree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ac.hxx
DEBUG_tools.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
DEBUG_tools.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
DEBUG_tools.c.o: $(ARBHOME)/INCLUDE/arbdb.h
DEBUG_tools.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o:  
DEBUG_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
DEBUG_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
DEBUG_tools.c.o: ac.hxx
