OBJECT=  main.o fconv.o mg.o genbank.o macke.o phylip.o paup.o \
	util.o date.o embl.o gcg.o printable.o alma.o \
	routines.o

.SUFFIXES: .o .c .cxx

$(ARBHOME)/bin/arb_convert_aln: $(OBJECT)
	$(ACC) $(cflags) -o $@ $(OBJECT)
.c.o:
	$(ACC) $(cflags) -c $< $(AINCLUDES)

proto:
	rm -f prototypes.h
	../MAKEBIN/aisc_mkpt -C $(OBJECT:.o=.c) >prototypes.h

depend:
	$(MAKEDEPEND) $(OBJECT:.o=.c*)

# DO NOT DELETE THIS LINE -- make depend depends on it.


alma.o:  
alma.o:  
alma.o:  
alma.o:   
alma.o:   
alma.o:  
alma.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
alma.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
alma.o: global.h prototypes.h
date.o:  
date.o:  
date.o:  
date.o:  
date.o:   
date.o:   
date.o:   
date.o:   
date.o: 
date.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
date.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
date.o: global.h prototypes.h
embl.o:  
embl.o:  
embl.o:  
embl.o:   
embl.o: 
embl.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
embl.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
embl.o: global.h prototypes.h
fconv.o:  
fconv.o:  
fconv.o:  
fconv.o:   
fconv.o: 
fconv.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
fconv.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
fconv.o: global.h prototypes.h
gcg.o:  
gcg.o:  
gcg.o:  
gcg.o:   
gcg.o: 
gcg.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
gcg.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
gcg.o: global.h prototypes.h
genbank.o:  
genbank.o:  
genbank.o:  
genbank.o:   
genbank.o:   
genbank.o:  
genbank.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
genbank.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
genbank.o: global.h prototypes.h
macke.o:  
macke.o:  
macke.o:  
macke.o:   
macke.o: 
macke.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
macke.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
macke.o: global.h prototypes.h
main.o:  
main.o:  
main.o:  
main.o:   
main.o:   
main.o:  
main.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
main.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
main.o: global.h prototypes.h
mg.o:  
mg.o:  
mg.o:  
mg.o:   
mg.o: 
mg.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
mg.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
mg.o: global.h prototypes.h
paup.o:  
paup.o:  
paup.o:  
paup.o:   
paup.o: 
paup.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
paup.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
paup.o: global.h prototypes.h
phylip.o:  
phylip.o:  
phylip.o:  
phylip.o:   
phylip.o: 
phylip.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
phylip.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
phylip.o: global.h prototypes.h
printable.o:  
printable.o:  
printable.o:  
printable.o:  
printable.o:  
printable.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
printable.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
printable.o: convert.h global.h prototypes.h
routines.o:  
routines.o:  
routines.o:  
routines.o:   
routines.o: 
routines.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
routines.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
routines.o: global.h prototypes.h
util.o:  
util.o:  
util.o:  
util.o:  
util.o:   
util.o:   
util.o:   
util.o:  
util.o:  
util.o:  
util.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
util.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h convert.h
util.o: global.h prototypes.h
