.SUFFIXES: .o .c

OBJECTS = clustalv.o amenu.o myers.o sequence.o showpair.o \
          upgma.o util.o trees.o gcgcheck.o


$(ARBHOME)/bin/clustalv : $(OBJECTS)
	$(ACC) $(cflags) -o $@ $(OBJECTS) -lm

.c.o:
	$(ACC) $(cflags) -c -o $@ $< $(AINCLUDES)

depend:
	makedepend $(MAKEDEPENDINC) $(OBJECTS:.o=.c)

# DO NOT DELETE THIS LINE -- make depend depends on it.


amenu.o:  
amenu.o:  
amenu.o:  
amenu.o:  
amenu.o:   
amenu.o:   
amenu.o:   
amenu.o:  
amenu.o:  
amenu.o:  
amenu.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
amenu.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h clustalv.h
amenu.o: general.h
clustalv.o:  
clustalv.o:  
clustalv.o:  
clustalv.o:  
clustalv.o:  
clustalv.o:  
clustalv.o:   
clustalv.o:  
clustalv.o:  
clustalv.o:  
clustalv.o: 
clustalv.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
clustalv.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
clustalv.o: clustalv.h general.h matrices.h
gcgcheck.o:  
gcgcheck.o:  
gcgcheck.o:   
gcgcheck.o:  
gcgcheck.o: 
gcgcheck.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
myers.o:  
myers.o:  
myers.o:  
myers.o:  
myers.o:  
myers.o:   
myers.o:   
myers.o:  
myers.o:  
myers.o:  
myers.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
myers.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h clustalv.h
myers.o: general.h
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o:   
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
sequence.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
sequence.o: clustalv.h general.h
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:   
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
showpair.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
showpair.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
showpair.o: clustalv.h general.h
trees.o:  
trees.o:  
trees.o:  
trees.o:  
trees.o:  
trees.o:  
trees.o:  
trees.o:   
trees.o:   
trees.o:  
trees.o:  
trees.o:   
trees.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
trees.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
trees.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h clustalv.h
trees.o: general.h
upgma.o:  
upgma.o:  
upgma.o:  
upgma.o:  
upgma.o:  
upgma.o:   
upgma.o:   
upgma.o:  
upgma.o:  
upgma.o:  
upgma.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
upgma.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h clustalv.h
upgma.o: general.h
util.o:  
util.o:  
util.o:  
util.o:  
util.o:  
util.o:   
util.o:   
util.o:   
util.o:   
util.o:  
util.o:   
util.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
util.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h clustalv.h
util.o: general.h
