/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef COMMON_H
#define COMMON_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* common.c */
const char *aisc_client_get_m_id(const char *path, char **m_name, int *id);
const char *aisc_get_m_id(const char *path, char **m_name, int *id);
const char *aisc_client_open_socket(const char *path, int delay, int do_connect, int *psocket, char **unix_name);
const char *aisc_open_socket(const char *path, int delay, int do_connect, int *psocket, char **unix_name);

#else
#error common.h included twice
#endif /* COMMON_H */
