/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef ARB_DIFF_H
#define ARB_DIFF_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* arb_diff.cxx */

#ifndef _GLIBCXX_CSTDLIB
#include <cstdlib>
#endif

bool ARB_textfiles_have_difflines(const char *file1, const char *file2, int expected_difflines, int special_mode);
size_t ARB_test_mem_equal(const unsigned char *buf1, const unsigned char *buf2, size_t common, size_t blockStartAddress);
bool ARB_files_are_equal(const char *file1, const char *file2);

#else
#error arb_diff.h included twice
#endif /* ARB_DIFF_H */
