#!/bin/sh
rm -f diff_archiv
tar cvf diff_archiv `find . -newer arbsrc* \
	! -name '*.o' \
	! -name '*.a' \
	! -name '*.ii' \
	! -name '*.arb' \
	! -name '*.gz' \
	! -name '*.so*' \
	! -name so_locations \
	! -type d \
	! -perm -100 \
	-print`