# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS = probe_design.o
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o: 
	$(CPP) $(cflags) -c -o $@ $(@:.o=.cxx)  $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

probe_design.o: 
probe_design.o:  
probe_design.o:  
probe_design.o:  
probe_design.o:  
probe_design.o:  
probe_design.o:  
probe_design.o:  $(ARBHOME)/INCLUDE/arbdb.h
probe_design.o: $(ARBHOME)/INCLUDE/ad_prot.h
probe_design.o: $(ARBHOME)/INCLUDE/arbdbt.h
probe_design.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
probe_design.o: $(ARBHOME)/INCLUDE/aw_root.hxx
probe_design.o: $(ARBHOME)/INCLUDE/aw_device.hxx
probe_design.o: $(ARBHOME)/INCLUDE/aw_window.hxx
probe_design.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
probe_design.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
probe_design.o: $(ARBHOME)/INCLUDE/awt.hxx
probe_design.o: $(ARBHOME)/INCLUDE/awt_iupac.hxx
probe_design.o: $(ARBHOME)/INCLUDE/PT_com.h
probe_design.o: $(ARBHOME)/INCLUDE/client.h
probe_design.o: $(ARBHOME)/INCLUDE/servercntrl.h probe_design.hxx
