#!/bin/sh
# Syntax arb_export [/beta]

dest=/trance1/ARB_download/ARB
destmach=$dest$1/$HOSTTYPE

FILES="arb_install.sh arb.tgz zcat"
echo "****************************************"
echo "exporting $FILES to $destmach"
for i in $FILES; do
    echo cp $i $destmach
    cp $i $destmach
done

echo "****************************************"
TODAY=`date +%Y_%m_%d`
echo cp -L arbsrc.tgz $dest/src/arbsrc_$TODAY.tgz
cp -L arbsrc.tgz $dest/src/arbsrc_$TODAY.tgz

README="arb_README.txt README arb_CHANGES.txt"
echo "****************************************"
echo "exporting $README to $dest"
for i in $README; do
    echo cp $i $dest
    cp $i $dest
done

# export names.dat:
echo "****************************************"
echo "exporting names.dat"
ARBHOME=${ARBHOME:-"/usr/arb"}
echo gzip <${ARBHOME}/lib/nas/names.dat >$dest/xtra/names.dat.gz
gzip <${ARBHOME}/lib/nas/names.dat >$dest/xtra/names.dat.gz
