#!/bin/sh

# This is a script that invokes Emacs, loads gene code, and does
# whatever the arguments said to do.  This script is modified by
# the people who created ARB

EMACS_19=$ARBHOME/DEPOT2/emacs

ALE_LISPDIR=$ARBHOME/DEPOT2/ALE
ALE_ARCHDIR=$ARBHOME/DEPOT2/ALE
ALE_DUMMYFILE=/tmp/arb_dummy_${USER}_${ARB_PID}.gdbm
export ALE_LISPDIR
export ALE_ARCHDIR

rm -f $ALE_DUMMYFILE
echo "This is a dummy file needed to cheat ale" >$ALE_DUMMYFILE
${EMACS_19} -q -l ${ALE_LISPDIR}/gene -f gene-startup -f gene-process-args $ALE_DUMMYFILE
rm -f $ALE_DUMMYFILE
