# ----------------------------------------------------------
#   _  _  __ _  __  ____    ____  ____  ____  ____  ____
#  / )( \(  ( \(  )(_  _)  (_  _)(  __)/ ___)(_  _)/ ___)
#  ) \/ (/    / )(   )(      )(   ) _) \___ \  )(  \___ \
#  \____/\_)__)(__) (__)    (__) (____)(____/ (__) (____/
#
# ----------------------------------------------------------


.SUFFIXES: .cxx .o .sym

dummy:
	false

# ----------------------------------------------------------

VALGRIND=0# only test
#VALGRIND=1# run valgrind after sucessful test
#VALGRIND=2# run valgrind before test (useful if test traps w/o any helpful information)

# ----------------------------------------------------------

# restrict tests to modules matching regexpr 'RESTRICT_MODULE': 
RESTRICT_MODULE='.'
#RESTRICT_MODULE='MG_species\.cxx'

# restrict tests to library with basename
RESTRICT_LIB=# run all tests
#RESTRICT_LIB=ARBDB# test only this library
#RESTRICT_LIB=FAST_ALIGNER# test only this library
#RESTRICT_LIB=MERGE# test only this library

# ----------------------------------------------------------

#WARN_LEVEL=0# disable warnings 
WARN_LEVEL=1# enable warnings (recommended)

# ----------------------------------------------------------

RELUNITDIR=../$(UNITDIR)
FULLUNITDIR=$(ARBHOME)/$(UNITDIR)

SHAREDLIBS=\
	ARBDB \
	AWT \
	WINDOW \

ISSHAREDLIB=$(findstring $(UNITDIR),$(SHAREDLIBS))

ifeq ($(ISSHAREDLIB),)
	UNITLIB=$(UNITLIBNAME).a
else
	UNITLIB=lib$(UNITLIBNAME).so
endif

UNIQUE_NAME=test_$(subst /,_,$(subst .,_,$(UNITDIR)_$(UNITLIB)))

FULLLIB=$(FULLUNITDIR)/$(UNITLIB)

DESTDIR=tests
RUNDIR=run
RUN2HERE=..# prefix from RUNDIR to here (UNIT_TESTER)

SYMLIST=$(DESTDIR)/$(UNIQUE_NAME).sym
TEST_CODE=$(DESTDIR)/$(UNIQUE_NAME).cxx
TEST_OBJ=$(DESTDIR)/$(UNIQUE_NAME).o
TEST_EXE=$(DESTDIR)/$(UNIQUE_NAME)

SYM2TESTCODE=./sym2testcode.pl

INCDIR=../INCLUDE

INCLUDES= \
	UnitTester.hxx \
	$(INCDIR)/arb_assert.h \

UNIT_TESTER_LIB=./UNIT_TESTER.a

ifeq ($(UNITLIB),.a)
LINKLIST=
LINKDEPS=
else
LINKLIST=$(shell ../SOURCE_TOOLS/needed_libs.pl -S -A .. -l $(FULLLIB))
LINKDEPS=$(shell ../SOURCE_TOOLS/needed_libs.pl -S -A .. -F $(FULLLIB))
endif

# --------------------------------------------------------------------------------

clean:
	rm -f $(DESTDIR)/*

# --------------------------------------------------------------------------------

$(DESTDIR):
	test -d $(DESTDIR) || mkdir -p $(DESTDIR)

$(RUNDIR):
	test -d $(RUNDIR) || mkdir -p $(RUNDIR)

makedirs: $(DESTDIR) $(RUNDIR)

$(SYMLIST) : $(FULLLIB) Makefile makedirs
	nm -C -l $< > $@

$(TEST_CODE) : $(SYMLIST) $(SYM2TESTCODE) 
	$(SYM2TESTCODE) $(UNITLIB) $(RESTRICT_MODULE) $< $@ $(WARN_LEVEL)

$(TEST_OBJ) : $(TEST_CODE) $(INCLUDES)
	$(CPP) $(cflags) -c $< -o $@ -I. 

$(TEST_EXE) : $(TEST_OBJ) $(UNIT_TESTER_LIB) $(LINKDEPS)
	$(LINK_EXECUTABLE) $@ $< $(UNIT_TESTER_LIB) -L../LIBLINK $(LINKLIST) $(EXECLIBS)

dump:
	@echo "$(SEP) dump $(UNITLIBNAME)"
	@echo "UNITDIR        ='$(UNITDIR)'"
	@echo "UNITLIBNAME    ='$(UNITLIBNAME)'"
	@echo "FULLUNITDIR    ='$(FULLUNITDIR)'"
	@echo "ISSHAREDLIB    ='$(ISSHAREDLIB)'"
	@echo "UNITLIB        ='$(UNITLIB)'"
	@echo "FULLLIB        ='$(FULLLIB)'"
	@echo "UNIQUE_NAME    ='$(UNIQUE_NAME)'"
	@echo "SYMLIST        ='$(SYMLIST)'"
	@echo "TEST_CODE      ='$(TEST_CODE)'"
	@echo "TEST_OBJ       ='$(TEST_OBJ)'"
	@echo "TEST_EXE       ='$(TEST_EXE)'"
	@echo "INCLUDES       ='$(INCLUDES)'"
	@echo "LINKLIST       ='$(LINKLIST)'"
	@echo "LINKDEPS       ='$(LINKDEPS)'"



perform_test: $(TEST_EXE)
	@echo "fake[3]: Entering directory \`$(FULLUNITDIR)'"
ifeq ($(VALGRIND),2)
	cd $(RUNDIR);$(ARBHOME)/SOURCE_TOOLS/arb_valgrind -l -c 15 $(RUN2HERE)/$(TEST_EXE)
endif
	cd $(RUNDIR);$(RUN2HERE)/$(TEST_EXE)
ifeq ($(COVERAGE),1)
	@echo "---------------------------------------- test-coverage for $(UNITLIBNAME)"
	./gcov2msg.pl $(FULLUNITDIR)
endif
ifeq ($(VALGRIND),1)
	cd $(RUNDIR);$(ARBHOME)/SOURCE_TOOLS/arb_valgrind -l -c 15 $(RUN2HERE)/$(TEST_EXE)
endif
	@echo "fake[3]: Leaving directory \`$(FULLUNITDIR)'"

skip_test:
	@echo "unit-tests completely skipped for '$(UNITLIBNAME)' (RESTRICT_LIB='$(RESTRICT_LIB)')"

# --------------------

RUN:=perform_test

ifneq ('$(RESTRICT_LIB)','')
ifneq ($(UNITLIBNAME),$(RESTRICT_LIB))
	RUN:=skip_test
endif
endif

runtest: $(RUN)

#runtest: dump

