.SUFFIXES: .o .c .cxx

OBJECT =  CAP2.o Restriction.o Zuk_to_gen.o count.o findall.o lsadt.o \
	sho_helix.o varpos.o


all: $(OBJECT:%.o=../../bin/%)

../../bin/%: %.c
	$(ACC) $(cflags) -o $@ $< $(AINCLUDES) $(LIB) -lm

depend:
	makedepend -o '' -p ../../bin/ $(MAKEDEPENDINC) $(OBJECT:.o=.c*)

# DO NOT DELETE THIS LINE -- make depend depends on it.


CAP2:  
CAP2:  
CAP2:  
CAP2:   
CAP2: 
CAP2: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CAP2: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
Restriction:  
Restriction:  
Restriction:  
Restriction:  
Restriction:  
Restriction: 
Restriction: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
Restriction: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h Flatio.c
Zuk_to_gen:  
Zuk_to_gen:  
Zuk_to_gen:  
Zuk_to_gen:   
Zuk_to_gen: 
Zuk_to_gen: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
Zuk_to_gen: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
count:  
count:  
count:  
count:  
count:  
count:   
count:   
count: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
count: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
count: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h Flatio.c
findall:  
findall:  
findall:  
findall:   
findall:  
findall: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
findall: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h Flatio.c
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:  
lsadt:   
lsadt:   
lsadt:   
lsadt:   
lsadt:  
lsadt:  
lsadt:   
lsadt: 
lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
lsadt: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
sho_helix:  
sho_helix:  
sho_helix:  
sho_helix:   
sho_helix:  
sho_helix: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
sho_helix: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h Flatio.c
varpos:  
varpos:  
varpos:  
varpos:   
varpos:  
varpos: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
varpos: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h Flatio.c
