#!/bin/sh
ARBMETA='/usr3/ARB'

arb_update $ARBMETA/source \
		$ARBMETA/sol1_opti \
		$ARBMETA/sol1_prof \
		$ARBMETA/sol2_opti \
		$ARBMETA/linux_debug \
		$ARBMETA/linux_opti
arb_update $ARBMETA/source -host hp8 arb
