/* This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef SERVER_H
#define SERVER_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* server.c */

#include <aisc_func_types.h>
#ifndef _STDIO_H
#include <stdio.h>
#endif

void aisc_server_errorf(const char *templat, ...) __ATTR__FORMAT(1);
const char *aisc_get_object_names(long i);
Hs_struct *open_aisc_server(const char *path, int timeout, int fork);
int aisc_talking_get_index(int u, int o);
long aisc_make_sets(long *obj);
int aisc_broadcast(Hs_struct *hs, int message_type, const char *message);
Hs_struct *aisc_accept_calls(Hs_struct *hs);
void aisc_server_shutdown(Hs_struct*& hs);
int aisc_add_destroy_callback(aisc_destroy_callback callback, long clientdata);
void aisc_remove_destroy_callback(void);
int aisc_server_save_token(FILE *fd, const char *buffer, int maxsize);
int aisc_server_load_token(FILE *fd, char *buffer, int maxsize);

#else
#error server.h included twice
#endif /* SERVER_H */
