# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS = edit.o edit_naligner.o edit_tools.o ed_conf.o
# edit_mgr_client.o 
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o: 
	$(CPP) $(cflags) -c -D_USE_AW_WINDOW $(@:.o=.cxx) $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


ed_conf.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
ed_conf.c.o: $(ARBHOME)/INCLUDE/adtools.hxx
ed_conf.c.o: $(ARBHOME)/INCLUDE/arbdb++.hxx
ed_conf.c.o: $(ARBHOME)/INCLUDE/arbdb.h
ed_conf.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ed_conf.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
ed_conf.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ed_conf.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ed_conf.c.o:  
ed_conf.c.o:  
ed_conf.c.o:  
ed_conf.c.o:  
ed_conf.c.o:  
ed_conf.c.o:  
ed_conf.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ed_conf.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h edit.hxx
edit.c.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
edit.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
edit.c.o: $(ARBHOME)/INCLUDE/adtools.hxx
edit.c.o: $(ARBHOME)/INCLUDE/arbdb++.hxx
edit.c.o: $(ARBHOME)/INCLUDE/arbdb.h
edit.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
edit.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
edit.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
edit.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
edit.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit.c.o: $(ARBHOME)/INCLUDE/awt.hxx
edit.c.o: $(ARBHOME)/INCLUDE/awt_map_key.hxx
edit.c.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx
edit.c.o: $(ARBHOME)/INCLUDE/gde.hxx
edit.c.o: $(ARBHOME)/INCLUDE/st_window.hxx
edit.c.o:  
edit.c.o:  
edit.c.o:  
edit.c.o:  
edit.c.o:  
edit.c.o:  
edit.c.o:   
edit.c.o:   
edit.c.o:  
edit.c.o:  
edit.c.o:  
edit.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
edit.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h ed_conf.hxx
edit.c.o: edit.hxx
edit_naligner.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit_naligner.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
edit_naligner.c.o: $(ARBHOME)/INCLUDE/arbdb.h
edit_naligner.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
edit_naligner.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
edit_naligner.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit_naligner.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit_naligner.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o:  
edit_naligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
edit_naligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
edit_tools.c.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
edit_tools.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit_tools.c.o: $(ARBHOME)/INCLUDE/adtools.hxx
edit_tools.c.o: $(ARBHOME)/INCLUDE/arbdb++.hxx
edit_tools.c.o: $(ARBHOME)/INCLUDE/arbdb.h
edit_tools.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit_tools.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
edit_tools.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit_tools.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o:  
edit_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
edit_tools.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
edit_tools.c.o: edit.hxx
