# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx
CPP_OBJECTS = edit.o edit_naligner.o edit_tools.o ed_conf.o
# edit_mgr_client.o 
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o: 
	$(CPP) $(cflags) -c -D_USE_AW_WINDOW $(@:.o=.cxx) $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

edit.o:   
edit.o:  
edit.o:  
edit.o:  
edit.o:   
edit.o:  
edit.o:  
edit.o:  
edit.o:   
edit.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
edit.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
edit.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
edit.o: $(ARBHOME)/INCLUDE/arbdb.h
edit.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit.o: $(ARBHOME)/INCLUDE/arbdbt.h
edit.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
edit.o: $(ARBHOME)/INCLUDE/arbdb++.hxx
edit.o: $(ARBHOME)/INCLUDE/adtools.hxx
edit.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
edit.o: $(ARBHOME)/INCLUDE/st_window.hxx ./edit.hxx
edit.o: ed_conf.hxx $(ARBHOME)/INCLUDE/awt_map_key.hxx
edit.o: $(ARBHOME)/INCLUDE/gde.hxx
edit.o: $(ARBHOME)/INCLUDE/awt.hxx
edit.o: $(ARBHOME)/INCLUDE/awtc_fast_aligner.hxx
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o:  
edit_naligner.o: $(ARBHOME)/INCLUDE/arbdb.h
edit_naligner.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit_naligner.o: $(ARBHOME)/INCLUDE/arbdbt.h
edit_naligner.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit_naligner.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
edit_naligner.o: 
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  
edit_tools.o:  $(ARBHOME)/INCLUDE/arbdb.h
edit_tools.o: $(ARBHOME)/INCLUDE/ad_prot.h
edit_tools.o: $(ARBHOME)/INCLUDE/arbdb++.hxx
edit_tools.o: $(ARBHOME)/INCLUDE/adtools.hxx
edit_tools.o: $(ARBHOME)/INCLUDE/aw_root.hxx
edit_tools.o: $(ARBHOME)/INCLUDE/aw_device.hxx
edit_tools.o: $(ARBHOME)/INCLUDE/aw_window.hxx
edit_tools.o: $(ARBHOME)/INCLUDE/BI_helix.hxx ./edit.hxx
ed_conf.o:  
ed_conf.o:  
ed_conf.o:  
ed_conf.o:  
ed_conf.o:  $(ARBHOME)/INCLUDE/arbdb.h
ed_conf.o: $(ARBHOME)/INCLUDE/ad_prot.h
ed_conf.o: $(ARBHOME)/INCLUDE/arbdb++.hxx
ed_conf.o: $(ARBHOME)/INCLUDE/adtools.hxx
ed_conf.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ed_conf.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ed_conf.o: $(ARBHOME)/INCLUDE/aw_window.hxx ./edit.hxx
