#!/bin/sh
#watch out for GS262 and DEPOT

rm -f arbdepot_*.tgz
(	find DEPOT2/GS262 ! -name '*.[oa]' ! -name gs -print; \
	find DEPOT2/emacs* ! -name '*.[oa]' ! \( -perm -100 -name 'emacs*' \) -print; \
	find DEPOT2/ale* -print; \
	find DEPOT2 -type l -print; \
	find DEPOT2/ALE DEPOT/ghostscript -print; \
	)|cpio -oH tar |gzip - >`date '+arbdepot_%d_%m_%y.tgz'`
