.SUFFIXES: .o .c .cxx
OBJECTS =	AW_xkey.o AW_xfont.o AW_nawar.o AW_button.o \
		AW_at.o AW_print.o AW_window.o \
		AW_device.o AW_Xm.o AW_click.o AW_size.o \
		AW_xfig.o AW_xfigfont.o AW_status.o AW_preset.o 

$(MAIN): $(OBJECTS)
	$(ARCPPLIB) $(@:.a=).$(SHARED_LIB_SUFFIX) $(OBJECTS)  
	touch $@
.cxx.o: 
	$(CCPLIB) $(cflags) -c $< $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:   
AW_Xm.c.o:   
AW_Xm.c.o:  
AW_Xm.c.o:  
AW_Xm.c.o:   
AW_Xm.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AW_Xm.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_Xm.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h aw_Xm.hxx
AW_Xm.c.o: aw_commn.hxx aw_device.hxx aw_root.hxx
AW_at.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_at.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_at.c.o:  
AW_at.c.o:  
AW_at.c.o:  
AW_at.c.o:   
AW_at.c.o:   
AW_at.c.o: 
AW_at.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_at.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h aw_at.hxx
AW_at.c.o: aw_device.hxx aw_root.hxx aw_window.hxx aw_xfig.hxx
AW_button.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_button.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AW_button.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_button.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:   
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o:  
AW_button.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_button.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_button.c.o: aw_Xm.hxx aw_at.hxx aw_awar.hxx aw_click.hxx aw_device.hxx
AW_button.c.o: aw_print.hxx aw_root.hxx aw_size.hxx aw_window.hxx
AW_button.c.o: aw_window_Xm.hxx
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:   
AW_click.c.o:   
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o:  
AW_click.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_click.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_click.c.o: aw_click.hxx aw_commn.hxx aw_device.hxx aw_root.hxx
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:   
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o:  
AW_device.c.o: 
AW_device.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_device.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_device.c.o: aw_commn.hxx aw_device.hxx aw_root.hxx aw_window.hxx
AW_nawar.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_nawar.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o:   
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o:  
AW_nawar.c.o: 
AW_nawar.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_nawar.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_nawar.c.o: aw_nawar.hxx aw_root.hxx
AW_preset.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_preset.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:   
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o:  
AW_preset.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_preset.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_preset.c.o: aw_device.hxx aw_preset.hxx aw_root.hxx aw_window.hxx
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:   
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o:  
AW_print.c.o: 
AW_print.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_print.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_print.c.o: aw_commn.hxx aw_device.hxx aw_print.hxx aw_root.hxx
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:   
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o:  
AW_size.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_size.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_size.c.o: aw_commn.hxx aw_device.hxx aw_root.hxx aw_size.hxx
AW_status.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_status.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o:  
AW_status.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_status.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_status.c.o: aw_device.hxx aw_root.hxx aw_window.hxx
AW_window.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_window.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AW_window.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_window.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:   
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o:  
AW_window.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_window.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_window.c.o: aw_Xm.hxx aw_at.hxx aw_awar.hxx aw_click.hxx aw_commn.hxx
AW_window.c.o: aw_device.hxx aw_keysym.hxx aw_print.hxx aw_root.hxx
AW_window.c.o: aw_size.hxx aw_window.hxx aw_window_Xm.hxx aw_xfig.hxx
AW_window.c.o: aw_xfigfont.hxx aw_xkey.hxx
AW_xfig.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_xfig.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:   
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o:  
AW_xfig.c.o: 
AW_xfig.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AW_xfig.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
AW_xfig.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_xfig.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_xfig.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
AW_xfig.c.o: aw_device.hxx aw_root.hxx aw_xfig.hxx
AW_xfigfont.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_xfigfont.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AW_xfigfont.c.o: $(ARBHOME)/INCLUDE/awt.hxx
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o:  
AW_xfigfont.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AW_xfigfont.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_xfigfont.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_xfigfont.c.o: aw_commn.hxx aw_device.hxx aw_root.hxx aw_window.hxx
AW_xfigfont.c.o: aw_xfig.hxx aw_xfigfont.hxx
AW_xfont.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_xfont.c.o: $(ARBHOME)/INCLUDE/arbdb.h 
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:   
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o:  
AW_xfont.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_xfont.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_xfont.c.o: aw_commn.hxx aw_device.hxx aw_root.hxx aw_xfont.hxx
AW_xkey.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AW_xkey.c.o: $(ARBHOME)/INCLUDE/arbdb.h 
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o:  
AW_xkey.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AW_xkey.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AW_xkey.c.o: aw_keysym.hxx aw_xkey.hxx
