# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx

CPP_OBJECTS = AWTC_next_neighbours.o AWTC_rename.o AWTC_names_admin.o \
	AWTC_seq_search.o AWTC_fast_aligner.o AWTC_ClustalV.o AWTC_constructSequence.o \
	AWTC_submission.o
# AWTC_names_client.o
$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o:
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


AWTC_ClustalV.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_ClustalV.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_ClustalV.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o: 
AWTC_ClustalV.c.o: 
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o:  
AWTC_ClustalV.c.o: 
AWTC_ClustalV.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
AWTC_ClustalV.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_ClustalV.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_ClustalV.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
AWTC_ClustalV.c.o: awtc_ClustalV.hxx awtc_assert.hxx awtc_seq_search.hxx
AWTC_constructSequence.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_constructSequence.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_constructSequence.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTC_constructSequence.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_constructSequence.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o: 
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o:  
AWTC_constructSequence.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_constructSequence.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_constructSequence.c.o: awtc_assert.hxx awtc_constructSequence.hxx
AWTC_constructSequence.c.o: awtc_fast_aligner.hxx awtc_seq_search.hxx
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_fast_aligner.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o:  
AWTC_fast_aligner.c.o: 
AWTC_fast_aligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
AWTC_fast_aligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
AWTC_fast_aligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_fast_aligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_fast_aligner.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
AWTC_fast_aligner.c.o: awtc_ClustalV.hxx awtc_assert.hxx awtc_fast_aligner.hxx
AWTC_fast_aligner.c.o: awtc_next_neighbours.hxx awtc_seq_search.hxx
AWTC_names_admin.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_names_admin.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_names_admin.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTC_names_admin.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_names_admin.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTC_names_admin.c.o: $(ARBHOME)/INCLUDE/awt.hxx
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o: 
AWTC_names_admin.c.o: 
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o:  
AWTC_names_admin.c.o: 
AWTC_names_admin.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_names_admin.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_names_admin.c.o: awtc_rename.hxx
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/PT_com.h
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/client.h
AWTC_next_neighbours.c.o: $(ARBHOME)/INCLUDE/servercntrl.h
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o:  
AWTC_next_neighbours.c.o: 
AWTC_next_neighbours.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_next_neighbours.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_next_neighbours.c.o: awtc_next_neighbours.hxx
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/client.h
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/names_client.h
AWTC_rename.c.o: $(ARBHOME)/INCLUDE/servercntrl.h
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o:  
AWTC_rename.c.o: 
AWTC_rename.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_rename.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_rename.c.o: awtc_rename.hxx
AWTC_seq_search.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_seq_search.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_seq_search.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o: 
AWTC_seq_search.c.o: 
AWTC_seq_search.c.o: 
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o:  
AWTC_seq_search.c.o: 
AWTC_seq_search.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/limits.h
AWTC_seq_search.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_seq_search.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTC_seq_search.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/syslimits.h
AWTC_seq_search.c.o: awtc_assert.hxx awtc_seq_search.hxx
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTC_submission.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTC_submission.c.o:  
AWTC_submission.c.o: 
AWTC_submission.c.o: 
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o:  
AWTC_submission.c.o: 
AWTC_submission.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTC_submission.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
