/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of ARB.xs. Do not edit this file, edit ARB.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "ARB.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "arbdb.h"
#include "arbdbt.h"
#include "ARB_ext.c"
#ifdef __cplusplus
}
#endif


#line 25 "ARB.c"
XS(XS_ARB_find)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: ARB::find(gbd, key, str, search_mode)");
    {
	GBDATA *	gbd;
	char *	key = (char *)SvPV(ST(1),PL_na);
	char *	str = (char *)SvPV(ST(2),PL_na);
	char *	search_mode = (char *)SvPV(ST(3),PL_na);
	GBDATA *	RETVAL;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 27 "ARB.xs"
	if (str[0] == 0) str = 0;
	if (key[0] == 0) key = 0;
	RETVAL = GB_find(gbd,key,str,GBP_search_mode(search_mode));
#line 48 "ARB.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "GBDATAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_search)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::search(gbd, str, type_of_entry)");
    {
	GBDATA *	gbd;
	char *	str = (char *)SvPV(ST(1),PL_na);
	char *	type_of_entry = (char *)SvPV(ST(2),PL_na);
	GBDATA *	RETVAL;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 41 "ARB.xs"
	if (str[0] == 0) str = 0;
	RETVAL = GB_search(gbd,str,GBP_gb_types(type_of_entry));
#line 75 "ARB.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "GBDATAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_create)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::create(father, key, type)");
    {
	GBDATA *	father;
	char *	key = (char *)SvPV(ST(1),PL_na);
	char *	type = (char *)SvPV(ST(2),PL_na);
	GBDATA *	RETVAL;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    father = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("father is not of type GBDATAPtr");
#line 53 "ARB.xs"
	RETVAL = GB_create(father,key,GBP_gb_types(type));
#line 101 "ARB.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "GBDATAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_first_marked)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::first_marked(gbd, keystring)");
    {
	GBDATA *	gbd;
	char *	keystring = (char *)SvPV(ST(1),PL_na);
	GBDATA *	RETVAL;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 63 "ARB.xs"
	if(keystring[0] == 0) keystring=0;
	RETVAL = GB_first_marked(gbd,keystring);
#line 127 "ARB.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "GBDATAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_next_marked)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::next_marked(gbd, keystring)");
    {
	GBDATA *	gbd;
	char *	keystring = (char *)SvPV(ST(1),PL_na);
	GBDATA *	RETVAL;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 74 "ARB.xs"
	if(keystring[0] == 0) keystring=0;
	RETVAL = GB_next_marked(gbd,keystring);
#line 153 "ARB.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "GBDATAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_read_string)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: ARB::read_string(gbd)");
    {
	GBDATA *	gbd;
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 84 "ARB.xs"
	RETVAL = GB_read_char_pntr(gbd);
#line 178 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_read_bits)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::read_bits(gbd, c_0, c_1)");
    {
	GBDATA *	gbd;
	char	c_0 = (char)*SvPV(ST(1),PL_na);
	char	c_1 = (char)*SvPV(ST(2),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 95 "ARB.xs"
	RETVAL = GB_read_bits_pntr(gbd,c_0,c_1);
#line 204 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_read_bytes)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: ARB::read_bytes(gbd)");
    {
	GBDATA *	gbd;
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 106 "ARB.xs"
	RETVAL = GB_read_bytes_pntr(gbd);
#line 228 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_read_ints_using_index)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::read_ints_using_index(gbd, index)");
    {
	GBDATA *	gbd;
	int	index = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 117 "ARB.xs"
	if( index >= GB_read_count(gbd)){
		croak("Error: ARB::read_ints_using_index index '%i' out of [0,%i[", index, GB_read_count(gbd));
	};
	RETVAL = GB_read_ints_pntr(gbd)[index];
#line 256 "ARB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_read_floats_using_index)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::read_floats_using_index(gbd, index)");
    {
	GBDATA *	gbd;
	int	index = (int)SvIV(ST(1));
	double	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 130 "ARB.xs"
	if( index >= GB_read_count(gbd)){
		croak("Error: ARB::read_ints_using_index index '%i' out of [0,%i[", index, GB_read_count(gbd));
	};
	RETVAL = GB_read_floats_pntr(gbd)[index];
#line 284 "ARB.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_ARB_write_ints_using_index)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::write_ints_using_index(gbd, val, index)");
    {
	GBDATA *	gbd;
	long	val = (long)SvIV(ST(1));
	long	index = (long)SvIV(ST(2));
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 144 "ARB.xs"
	RETVAL = "Not Implemented"; /* GB_write_ints(gbd,i,size);*/
#line 310 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_write_floats_using_index)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::write_floats_using_index(gbd, f, index)");
    {
	GBDATA *	gbd;
	double	f = (double)SvNV(ST(1));
	long	index = (long)SvIV(ST(2));
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 155 "ARB.xs"
	RETVAL = "Not Implemented"; /*GB_write_floats(gbd,f,size);*/
#line 336 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_read_type)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: ARB::read_type(gbd)");
    {
	GBDATA *	gbd;
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 165 "ARB.xs"
	RETVAL = GBP_type_to_string(GB_read_type(gbd));
#line 360 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_add_callback)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::add_callback(gbd, func_name, clientdata)");
    {
	GBDATA *	gbd;
	char *	func_name = (char *)SvPV(ST(1),PL_na);
	char *	clientdata = (char *)SvPV(ST(2),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 176 "ARB.xs"
	RETVAL = (char *)GBP_add_callback(gbd,func_name,clientdata);
#line 386 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_ensure_callback)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::ensure_callback(gbd, func_name, clientdata)");
    {
	GBDATA *	gbd;
	char *	func_name = (char *)SvPV(ST(1),PL_na);
	char *	clientdata = (char *)SvPV(ST(2),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 187 "ARB.xs"
	RETVAL = (char *)GBP_ensure_callback(gbd,func_name,clientdata);
#line 412 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_usleep)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: ARB::usleep(usec)");
    SP -= items;
    {
	long	usec = (long)SvIV(ST(0));
#line 196 "ARB.xs"
	GB_usleep(usec);
#line 428 "ARB.c"
	PUTBACK;
	return;
    }
}

XS(XS_ARB_remove_callback)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::remove_callback(gbd, func_name, clientdata)");
    {
	GBDATA *	gbd;
	char *	func_name = (char *)SvPV(ST(1),PL_na);
	char *	clientdata = (char *)SvPV(ST(2),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gbd = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gbd is not of type GBDATAPtr");
#line 206 "ARB.xs"
	RETVAL = (char *)GBP_remove_callback(gbd,func_name,clientdata);
#line 454 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_request_undo_type)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::request_undo_type(gb_main, type)");
    {
	GBDATA *	gb_main;
	char *	type = (char *)SvPV(ST(1),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gb_main = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gb_main is not of type GBDATAPtr");
#line 216 "ARB.xs"
	RETVAL = (char *)GB_request_undo_type(gb_main,GBP_undo_types(type));
#line 479 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_undo)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::undo(gb_main, type)");
    {
	GBDATA *	gb_main;
	char *	type = (char *)SvPV(ST(1),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gb_main = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gb_main is not of type GBDATAPtr");
#line 226 "ARB.xs"
	RETVAL = (char *)GB_undo(gb_main,GBP_undo_types(type));
#line 504 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_undo_info)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: ARB::undo_info(gb_main, type)");
    {
	GBDATA *	gb_main;
	char *	type = (char *)SvPV(ST(1),PL_na);
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gb_main = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gb_main is not of type GBDATAPtr");
#line 236 "ARB.xs"
	if (static_pntr) free(static_pntr);
	static_pntr = GB_undo_info(gb_main,GBP_undo_types(type));
	RETVAL = static_pntr;
#line 531 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_get_requested_undo_type)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: ARB::get_requested_undo_type(gb_main)");
    {
	GBDATA *	gb_main;
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gb_main = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gb_main is not of type GBDATAPtr");
#line 247 "ARB.xs"
	RETVAL = (char *)GBP_undo_type_2_string(GB_get_requested_undo_type(gb_main));
#line 555 "ARB.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_ARB_P2AT_open_table_field)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: ARB::P2AT_open_table_field(gb_table, key, type)");
    {
	GBDATA *	gb_table;
	char *	key = (char *)SvPV(ST(1),PL_na);
	char *	type = (char *)SvPV(ST(2),PL_na);
	GBDATA *	RETVAL;

	if (sv_derived_from(ST(0), "GBDATAPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gb_table = INT2PTR(GBDATA *,tmp);
	}
	else
	    croak("gb_table is not of type GBDATAPtr");
#line 258 "ARB.xs"
	RETVAL = GBT_open_table_field(gb_table,key,GBP_gb_types(type));
#line 580 "ARB.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "GBDATAPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_ARB)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("ARB::find", XS_ARB_find, file, "$$$$");
        newXSproto("ARB::search", XS_ARB_search, file, "$$$");
        newXSproto("ARB::create", XS_ARB_create, file, "$$$");
        newXSproto("ARB::first_marked", XS_ARB_first_marked, file, "$$");
        newXSproto("ARB::next_marked", XS_ARB_next_marked, file, "$$");
        newXSproto("ARB::read_string", XS_ARB_read_string, file, "$");
        newXSproto("ARB::read_bits", XS_ARB_read_bits, file, "$$$");
        newXSproto("ARB::read_bytes", XS_ARB_read_bytes, file, "$");
        newXSproto("ARB::read_ints_using_index", XS_ARB_read_ints_using_index, file, "$$");
        newXSproto("ARB::read_floats_using_index", XS_ARB_read_floats_using_index, file, "$$");
        newXSproto("ARB::write_ints_using_index", XS_ARB_write_ints_using_index, file, "$$$");
        newXSproto("ARB::write_floats_using_index", XS_ARB_write_floats_using_index, file, "$$$");
        newXSproto("ARB::read_type", XS_ARB_read_type, file, "$");
        newXSproto("ARB::add_callback", XS_ARB_add_callback, file, "$$$");
        newXSproto("ARB::ensure_callback", XS_ARB_ensure_callback, file, "$$$");
        newXSproto("ARB::usleep", XS_ARB_usleep, file, "$");
        newXSproto("ARB::remove_callback", XS_ARB_remove_callback, file, "$$$");
        newXSproto("ARB::request_undo_type", XS_ARB_request_undo_type, file, "$$");
        newXSproto("ARB::undo", XS_ARB_undo, file, "$$");
        newXSproto("ARB::undo_info", XS_ARB_undo_info, file, "$$");
        newXSproto("ARB::get_requested_undo_type", XS_ARB_get_requested_undo_type, file, "$");
        newXSproto("ARB::P2AT_open_table_field", XS_ARB_P2AT_open_table_field, file, "$$$");
    XSRETURN_YES;
}

