/* Merge tool external interface.
 *
 * This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef MG_MERGE_HXX
#define MG_MERGE_HXX

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* MG_main.cxx */

// source and destination DBs for merge:
extern GBDATA *GLOBAL_gb_src;
extern GBDATA *GLOBAL_gb_dst;

void MERGE_start_cb2(AW_window *aww, AW_root *aw_root, bool save_enabled, bool dest_is_new);
void MERGE_create_all_awars(AW_root *awr, AW_default aw_def, const char *fname_one, const char *fname_two);
AW_window *MERGE_create_main_window(AW_root *aw_root);

/* MG_species.cxx */
GB_ERROR MERGE_sequences_simple(AW_root *awr);

#else
#error mg_merge.hxx included twice
#endif /* MG_MERGE_HXX */
