# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c .cxx

OBJECTS = AC_main.o AC_tree.o AC_sequence.o DEBUG_tools.o AC_toys_n_tools.o

$(MAIN): $(OBJECTS)
	$(AR) $(MAIN) $(OBJECTS)

AC_sequence.o: AC_sequence.cxx 
	CC -O $(cflags) -c $< $(CPPINCLUDES)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

AC_main.o:  
AC_main.o:  
AC_main.o:  
AC_main.o:  
AC_main.o:   
AC_main.o:  
AC_main.o:  
AC_main.o:  
AC_main.o:   
AC_main.o:  $(ARBHOME)/INCLUDE/arbdb.h
AC_main.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_main.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_main.o: $(ARBHOME)/INCLUDE/ad_t_prot.h ac.hxx
AC_tree.o:  
AC_tree.o:  
AC_tree.o:  
AC_tree.o:  
AC_tree.o:   
AC_tree.o:  
AC_tree.o:  
AC_tree.o:  
AC_tree.o:   
AC_tree.o:  
AC_tree.o:  
AC_tree.o:  $(ARBHOME)/INCLUDE/arbdb.h
AC_tree.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_tree.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_tree.o: $(ARBHOME)/INCLUDE/ad_t_prot.h ac.hxx
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o:  
AC_sequence.o: $(ARBHOME)/INCLUDE/arbdb.h
AC_sequence.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_sequence.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_sequence.o: $(ARBHOME)/INCLUDE/ad_t_prot.h ac.hxx
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  
DEBUG_tools.o:  $(ARBHOME)/INCLUDE/arbdb.h
DEBUG_tools.o: $(ARBHOME)/INCLUDE/ad_prot.h
DEBUG_tools.o: $(ARBHOME)/INCLUDE/arbdbt.h
DEBUG_tools.o: $(ARBHOME)/INCLUDE/ad_t_prot.h ac.hxx
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o:  
AC_toys_n_tools.o: 
AC_toys_n_tools.o: $(ARBHOME)/INCLUDE/arbdb.h
AC_toys_n_tools.o: $(ARBHOME)/INCLUDE/ad_prot.h
AC_toys_n_tools.o: $(ARBHOME)/INCLUDE/arbdbt.h
AC_toys_n_tools.o: $(ARBHOME)/INCLUDE/ad_t_prot.h ac.hxx
