.SUFFIXES: .o .c

OBJECT = fastDNAml_1_0_6.o

$(ARBHOME)/bin/fastdnaml: $(OBJECT)
	$(ACC) $(cflags) -o $@ $< $(LIB) -lm

.c.o:
	$(ACC) $(cflags) -c -o $@ $< $(AINCLUDES)

depend:
	makedepend $(MAKEDEPENDINC) $(OBJECT:.o=.c)

# DO NOT DELETE THIS LINE -- make depend depends on it.

fastDNAml_1_0_6.o:  
fastDNAml_1_0_6.o:  
fastDNAml_1_0_6.o:  
fastDNAml_1_0_6.o:  
fastDNAml_1_0_6.o:  
fastDNAml_1_0_6.o:  
fastDNAml_1_0_6.o: fastDNAml_1_0.h
