.SUFFIXES: .o .c

OBJECT = fastdnaml.o 

$(ARBHOME)/bin/fastdnaml: $(OBJECT)
	$(ACC) $(cflags) -o $@ $(@F).o $(LIB) -lm

.c.o:
	$(ACC) $(cflags) -c -o $@ $< $(AINCLUDES)

depend:
	makedepend $(MAKEDEPENDINC) $(OBJECT:.o=.c)

# DO NOT DELETE THIS LINE -- make depend depends on it.


fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:   
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o:  
fastdnaml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
fastdnaml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
fastdnaml.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
fastdnaml.o: fastDNAml_1_0.h
