# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c

include AD_MOBJECTS.h

ACC_OBJECTS = $(GB_O) $(GB_T)

$(MAIN): $(ACC_OBJECTS)
	$(ARLIB) $(@:.a=).$(SHARED_LIB_SUFFIX) $(ACC_OBJECTS)
	touch $@
.c.o:
	$(CCLIB) $(cflags) -c $< $(AINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(ACC_OBJECTS:.o=.c)
links:
	ln -s ../ARBDB/*.[ch] .

# DO NOT DELETE THIS LINE -- make depend depends on it.

adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:   
adsort.o:  
adsort.o:  
adsort.o:  
adsort.o:   
adsort.o:  arbdb.h ./ad_prot.h arbdbt.h ./ad_t_prot.h
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:   
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:  
adlang1.o:   
adlang1.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adlang1.o: adlmacros.h arbdbt.h ./ad_t_prot.h
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:   
adstring.o: adlocal.h arbdb.h ./ad_prot.h adtune.h adlmacros.h arbdbt.h
adstring.o: ./ad_t_prot.h  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o:  
adstring.o: 
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:   
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:   
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  
arbdb.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
arbdb.o: adlmacros.h
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:   
ad_core.o:  
ad_core.o:  
ad_core.o:  
ad_core.o:   
ad_core.o: adlocal.h arbdb.h ./ad_prot.h adtune.h adlmacros.h
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:  
admath.o:   
admath.o:  
admath.o:  
admath.o:  
admath.o:  adlocal.h arbdb.h ./ad_prot.h
admath.o: adtune.h adlmacros.h
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  
adoptimize.o:  adlocal.h arbdb.h ./ad_prot.h
adoptimize.o: adtune.h adlmacros.h
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:  
adsystem.o:   adlocal.h
adsystem.o: arbdb.h ./ad_prot.h adtune.h adlmacros.h arbdbt.h ./ad_t_prot.h
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:   
adindex.o:  
adindex.o:  
adindex.o:  
adindex.o:   
adindex.o: adlocal.h arbdb.h ./ad_prot.h adtune.h adlmacros.h adlundo.h
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:  
adperl.o:   
adperl.o:  
adperl.o:  
adperl.o:   arbdb.h
adperl.o: ./ad_prot.h
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:   
adlink.o:  
adlink.o:  
adlink.o:  
adlink.o:   adlocal.h arbdb.h
adlink.o: ./ad_prot.h adtune.h adlmacros.h
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:   
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o:  
adsocket.o: adlocal.h arbdb.h ./ad_prot.h adtune.h adlmacros.h
adsocket.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adcomm.o: adlmacros.h  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:   
adcomm.o:  
adcomm.o:  
adcomm.o:  
adcomm.o:  
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:   
adhash.o:  
adhash.o:  
adhash.o:  
adhash.o:   
adhash.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adhash.o: adlmacros.h
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:   
adquery.o:  
adquery.o:  
adquery.o:  
adquery.o:   
adquery.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adquery.o: adlmacros.h
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:  
ad_save_load.o:   adlocal.h
ad_save_load.o: arbdb.h ./ad_prot.h adtune.h adlmacros.h admap.h
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:   
adcompr.o:  
adcompr.o:  
adcompr.o:  
adcompr.o:   
adcompr.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adcompr.o: adlmacros.h arbdbt.h ./ad_t_prot.h
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:  
admalloc.o:   
admalloc.o:  
admalloc.o:  
admalloc.o: adlocal.h arbdb.h ./ad_prot.h adtune.h adlmacros.h
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:   
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:   
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  
ad_load.o:  adlocal.h arbdb.h ./ad_prot.h
ad_load.o: adtune.h adlmacros.h admap.h
admap.o:  
admap.o:  
admap.o:  
admap.o:  
admap.o:   
admap.o:  
admap.o:  
admap.o:  
admap.o:   adlocal.h arbdb.h
admap.o: ./ad_prot.h adtune.h adlmacros.h admap.h
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:   
adTest.o:  
adTest.o:  
adTest.o:  
adTest.o:   
adTest.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adTest.o: adlmacros.h admap.h
adtune.o: adtune.h
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:   
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:   
adtools.o:  
adtools.o:  
adtools.o:  
adtools.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adtools.o: adlmacros.h arbdbt.h ./ad_t_prot.h
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:  
adseqcompr.o:   adlocal.h arbdb.h
adseqcompr.o: ./ad_prot.h adtune.h adlmacros.h arbdbt.h ./ad_t_prot.h
adseqcompr.o: adseqcompr.h
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  
adtables.o:  adlocal.h arbdb.h ./ad_prot.h adtune.h
adtables.o: adlmacros.h arbdbt.h ./ad_t_prot.h
