# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx

CPP_OBJECTS = AWTI_import.o \
		      AWTI_export.o \

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o:
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  
AWTI_import.o:  $(ARBHOME)/INCLUDE/arbdb.h
AWTI_import.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTI_import.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTI_import.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTI_import.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTI_import.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTI_import.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTI_import.o: $(ARBHOME)/INCLUDE/awt.hxx
AWTI_import.o: $(ARBHOME)/INCLUDE/GEN.hxx awti_import.hxx
AWTI_import.o: $(ARBHOME)/INCLUDE/awtc_rename.hxx
AWTI_import.o: awti_imp_local.hxx
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o:  
AWTI_export.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTI_export.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTI_export.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTI_export.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTI_export.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTI_export.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTI_export.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTI_export.o: $(ARBHOME)/INCLUDE/awt.hxx awti_export.hxx
AWTI_export.o: awti_exp_local.hxx
