# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .cxx

CPP_OBJECTS = AWTI_import.o \
		      AWTI_export.o \

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)
.cxx.o:
	$(CPP) $(cflags) -c $<  $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


AWTI_export.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTI_export.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTI_export.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTI_export.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTI_export.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTI_export.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTI_export.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTI_export.c.o: $(ARBHOME)/INCLUDE/awt.hxx
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o: 
AWTI_export.c.o: 
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o:  
AWTI_export.c.o: 
AWTI_export.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTI_export.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTI_export.c.o: awti_exp_local.hxx awti_export.hxx
AWTI_import.c.o: $(ARBHOME)/INCLUDE/GEN.hxx
AWTI_import.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
AWTI_import.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
AWTI_import.c.o: $(ARBHOME)/INCLUDE/arbdb.h
AWTI_import.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
AWTI_import.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
AWTI_import.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
AWTI_import.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
AWTI_import.c.o: $(ARBHOME)/INCLUDE/awt.hxx
AWTI_import.c.o: $(ARBHOME)/INCLUDE/awtc_rename.hxx
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o: 
AWTI_import.c.o: 
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o:  
AWTI_import.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
AWTI_import.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
AWTI_import.c.o: awti_imp_local.hxx awti_import.hxx
