# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx

CPP_OBJECTS =   ST_quality.o ST_ml.o ST_window.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)



# DO NOT DELETE THIS LINE -- make depend depends on it.


ST_ml.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
ST_ml.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ST_ml.c.o: $(ARBHOME)/INCLUDE/arbdb.h
ST_ml.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
ST_ml.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ST_ml.c.o: $(ARBHOME)/INCLUDE/awt_csp.hxx
ST_ml.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
ST_ml.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:   
ST_ml.c.o:   
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o:  
ST_ml.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
ST_ml.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ST_ml.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h st_ml.hxx
ST_quality.c.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
ST_quality.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
ST_quality.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ST_quality.c.o: $(ARBHOME)/INCLUDE/arbdb.h
ST_quality.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
ST_quality.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ST_quality.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ST_quality.c.o: $(ARBHOME)/INCLUDE/awt_csp.hxx
ST_quality.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
ST_quality.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:   
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o:  
ST_quality.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/float.h
ST_quality.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ST_quality.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
ST_quality.c.o: st_ml.hxx st_quality.hxx st_window.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
ST_window.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
ST_window.c.o: $(ARBHOME)/INCLUDE/arbdb.h
ST_window.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
ST_window.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/awt.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/awt_csp.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/awt_pro_a_nucs.hxx
ST_window.c.o: $(ARBHOME)/INCLUDE/awt_tree.hxx
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o:   
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o:  
ST_window.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
ST_window.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
ST_window.c.o: st_ml.hxx st_quality.hxx st_window.hxx
