#!/bin/bash

help() {
	echo ''
	echo 'This script fixes some bugs in older ARB versions (they fail to compile)'
	echo 'Use this when youve checked out an older version from cvs.'
	echo 'Do NOT use otherwise!'
	echo ''
	echo ' 1. cvs -d /trance1/REPOSITORY co -D yyyy/mm/dd ARB '
	echo ' 2. setarb'
	echo ' 3. setup the config.makefile'
	echo ' 4. prep_old_arb_versions iamsure'
	echo ' 5. make all'
	echo ''
}

if [ -z $1 ] ; then
	help
else
	if [ $1 = 'iamsure' ] ; then
		echo 'Fixing bugs'
		( cd $ARBHOME; \
			(cd NAMES_COM ; mkdir O; mkdir GENH; mkdir GENC ); \
			mkdir INCLUDE; \
			mkdir LIBLINK; \
			mkdir MAKEBIN; \
			(cd PROBE_COM ; mkdir GENH; mkdir GENC; mkdir O ); \
			(cd ORS_COM ; mkdir GENH; mkdir GENC; mkdir O ); \
		)
		echo ok
	else
		help
		echo 'Usage: prep_old_arb_versions iamsure'
		echo ''
	fi
fi
	
