/* ARB perl interface.
 *
 * This file is generated by aisc_mkpt.
 * Any changes you make here will be overwritten later!
 */

#ifndef AD_P_PROT_H
#define AD_P_PROT_H

/* define ARB attributes: */
#ifndef ATTRIBUTES_H
# include <attributes.h>
#endif


/* adperl.cxx */
const char *GBP_GB_SEARCH_TYPE_2_charPtr(GB_SEARCH_TYPE search_type);
GB_SEARCH_TYPE GBP_charPtr_2_GB_SEARCH_TYPE(const char *search_mode);
const char *GBP_GB_TYPES_2_charPtr(GB_TYPES type);
GB_TYPES GBP_charPtr_2_GB_TYPES(const char *type_name);
const char *GBP_GB_UNDO_TYPE_2_charPtr(GB_UNDO_TYPE undo_type);
GB_UNDO_TYPE GBP_charPtr_2_GB_UNDO_TYPE(const char *undo_type);
const char *GBP_GB_CASE_2_charPtr(GB_CASE sensitivity);
GB_CASE GBP_charPtr_2_GB_CASE(const char *sensitivity);
const char *GBP_GB_alignment_type_2_charPtr(GB_alignment_type ali_type);
GB_alignment_type GBP_charPtr_2_GB_alignment_type(const char *ali_type);

#else
#error ad_p_prot.h included twice
#endif /* AD_P_PROT_H */
