OBJECT = readseq.o ureadseq.o

.SUFFIXES: .o .c .cxx

all: $(ARBHOME)/bin/arb_readseq

$(ARBHOME)/bin/arb_readseq:  $(OBJECT)
	$(ACC) $(cflags) -o $@ $(OBJECT) 

.c.o:
	$(ACC) $(cflags) -c $< $(AINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJECT:.o=.c*)

# DO NOT DELETE THIS LINE -- make depend depends on it.

readseq.o:  
readseq.o:  
readseq.o:  
readseq.o:  
readseq.o:   
readseq.o:  ureadseq.h
ureadseq.o:  
ureadseq.o:  
ureadseq.o:  
ureadseq.o:  
ureadseq.o:   
ureadseq.o:  ureadseq.h
