# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx


CPP_OBJECTS = SEC_graphic.o SEC_main.o SEC_io.o SEC_read.o SEC_split.o SEC_paint.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)

# DO NOT DELETE THIS LINE -- make depend depends on it.

SEC_graphic.o: 
SEC_graphic.o: 
SEC_graphic.o:  
SEC_graphic.o:  
SEC_graphic.o: 
SEC_graphic.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_graphic.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_graphic.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEC_graphic.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEC_graphic.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/awt.hxx
SEC_graphic.o: $(ARBHOME)/INCLUDE/BI_helix.hxx sec_graphic.hxx
SEC_graphic.o:  secedit.hxx
SEC_graphic.o: 
SEC_main.o: 
SEC_main.o:  
SEC_main.o:  
SEC_main.o: 
SEC_main.o: 
SEC_main.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_main.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_main.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEC_main.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEC_main.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/awt.hxx
SEC_main.o: $(ARBHOME)/INCLUDE/BI_helix.hxx sec_graphic.hxx
SEC_main.o:  secedit.hxx
SEC_io.o: 
SEC_io.o: 
SEC_io.o: 
SEC_io.o:  
SEC_io.o:  
SEC_io.o:  
SEC_io.o:  
SEC_io.o:  
SEC_io.o:  
SEC_io.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_io.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_io.o: $(ARBHOME)/INCLUDE/aw_root.hxx secedit.hxx
SEC_read.o: 
SEC_read.o: 
SEC_read.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_read.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_read.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_read.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_read.o:  
SEC_read.o:  
SEC_read.o:  
SEC_read.o:  secedit.hxx
SEC_split.o: 
SEC_split.o:  
SEC_split.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_split.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_split.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_split.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_split.o:  secedit.hxx
SEC_paint.o:  
SEC_paint.o:  
SEC_paint.o: 
SEC_paint.o:  
SEC_paint.o: 
SEC_paint.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_paint.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_paint.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_paint.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_paint.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEC_paint.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
SEC_paint.o: $(ARBHOME)/INCLUDE/BI_helix.hxx secedit.hxx
SEC_paint.o: sec_graphic.hxx 
