# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben

.SUFFIXES: .o .cxx


CPP_OBJECTS = SEC_graphic.o SEC_main.o SEC_io.o SEC_read.o SEC_split.o SEC_paint.o

$(MAIN): $(CPP_OBJECTS)
	$(AR) $(MAIN) $(CPP_OBJECTS)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)

depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)

# DO NOT DELETE THIS LINE -- make depend depends on it.


SEC_graphic.c.o: $(ARBHOME)/INCLUDE/BI_helix.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/awt.hxx
SEC_graphic.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:   
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o:  
SEC_graphic.c.o: 
SEC_graphic.c.o: 
SEC_graphic.c.o: 
SEC_graphic.c.o: sec_graphic.hxx secedit.hxx
SEC_io.c.o: $(ARBHOME)/INCLUDE/ad_prot.h $(ARBHOME)/INCLUDE/arbdb.h
SEC_io.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx 
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:   
SEC_io.c.o:   
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o:  
SEC_io.c.o: 
SEC_io.c.o: 
SEC_io.c.o: 
SEC_io.c.o: secedit.hxx
SEC_main.c.o: ../EDIT4/ed4_class.hxx ../EDIT4/ed4_defs.hxx
SEC_main.c.o: ../EDIT4/ed4_search.hxx $(ARBHOME)/INCLUDE/BI_helix.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_main.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
SEC_main.c.o: $(ARBHOME)/INCLUDE/arbdb.h $(ARBHOME)/INCLUDE/arbdbt.h
SEC_main.c.o: $(ARBHOME)/INCLUDE/aw_awars.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/aw_preset.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/awt.hxx
SEC_main.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx 
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:   
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o:  
SEC_main.c.o: 
SEC_main.c.o: 
SEC_main.c.o: 
SEC_main.c.o: 
SEC_main.c.o: sec_graphic.hxx secedit.hxx
SEC_paint.c.o: ../EDIT4/ed4_class.hxx ../EDIT4/ed4_defs.hxx
SEC_paint.c.o: ../EDIT4/ed4_search.hxx $(ARBHOME)/INCLUDE/BI_helix.hxx
SEC_paint.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_paint.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_paint.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_paint.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx
SEC_paint.c.o: $(ARBHOME)/INCLUDE/aw_window.hxx
SEC_paint.c.o: $(ARBHOME)/INCLUDE/awt_canvas.hxx 
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o:  
SEC_paint.c.o: 
SEC_paint.c.o: 
SEC_paint.c.o: 
SEC_paint.c.o: 
SEC_paint.c.o: 
SEC_paint.c.o: 
SEC_paint.c.o: sec_graphic.hxx secedit.hxx
SEC_read.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_read.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_read.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_read.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx 
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:   
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o:  
SEC_read.c.o: 
SEC_read.c.o: 
SEC_read.c.o: 
SEC_read.c.o: 
SEC_read.c.o: secedit.hxx
SEC_split.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
SEC_split.c.o: $(ARBHOME)/INCLUDE/arbdb.h
SEC_split.c.o: $(ARBHOME)/INCLUDE/aw_device.hxx
SEC_split.c.o: $(ARBHOME)/INCLUDE/aw_root.hxx 
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:   
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o:  
SEC_split.c.o: 
SEC_split.c.o: 
SEC_split.c.o: 
SEC_split.c.o: secedit.hxx
