# Makefile May 2004 by Alexandros P. Stamatakis

CC = icc

CFLAGS = -O3 -static -DNORMAL -mp
CFLAGS_OMP = -O3  -DOPEN_MP -static -w -openmp
CFLAGS_MKL =  -O3 -static -I/opt/intel/mkl72/include/ -L/opt/intel/mkl72/lib/32/ -DMKL


RM = rm -f

all : raxml.i consense raxmlOMP.i raxmlMKL.i

consense : consense.o cons.o phylip.o
	$(CC) $(CFLAGS)	-o consense -lm consense.o phylip.o cons.o

raxml.i :  axml.o dnapars.o rev_functions.o 
	$(CC) $(CFLAGS) -o  raxml.i axml.o dnapars.o rev_functions.o -lm 

raxmlOMP.i :axmlOMP.o dnaparsOMP.o rev_functions.o
	$(CC) $(CFLAGS_OMP) -o raxmlOMP.i axmlOMP.o dnaparsOMP.o rev_functions.o -lm

raxmlMKL.i : axmlMKL.o dnapars.o rev_functions.o 
	$(CC) $(CFLAGS_MKL) -o  raxmlMKL.i axmlMKL.o dnapars.o rev_functions.o -lm -lmkl_ia32 -lguide -lpthread 

rev_functions.o : rev_functions.c
	$(CC) -c  rev_functions.c -o rev_functions.o 

consense.o : consense.c cons.h phylip.h
	$(CC) $(CFLAGS) -c consense.c


cons.o : cons.c cons.h phylip.h
	$(CC) $(CFLAGS) -c cons.c

phylip.o : phylip.c phylip.h
	$(CC) $(CFLAGS) -c phylip.c

axml.o : axml.c axml.h
	$(CC) $(CFLAGS) -c  axml.c -o axml.o

axmlOMP.o : axml.c axml.h
	$(CC) $(CFLAGS_OMP)  -c  axml.c -o axmlOMP.o

axmlMKL.o : axml.c axml.h
	$(CC) $(CFLAGS_MKL)  -c  axml.c -o axmlMKL.o

dnapars.o : dnapars.c phylip2.h
	$(CC) $(CFLAGS) -c dnapars.c 

dnaparsOMP.o : dnapars.c phylip2.h
	$(CC) $(CFLAGS_OMP) -c dnapars.c -o dnaparsOMP.o


clean : 
	$(RM) *.o
	$(RM) raxml.i raxmlOMP.i raxmlMKL.i consense
