# INCLUDE und GLOBALS MAIN CC cflags werden von aussen uebergeben
.SUFFIXES: .o .c .cxx
CPP_OBJECTS = adtsequence.o adt_edit.o adtali.o adextended.o adseq.o adspecies.o admain.o adali.o  liste.o 
$(MAIN): $(CPP_OBJECTS)
	$(ARLIB) $(@:.a=).$(SHARED_LIB_SUFFIX) $(CPP_OBJECTS)
	touch $@
.cxx.o: 
	$(CCPLIB) $(cflags) -c $< $(CPPINCLUDES)
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(CPP_OBJECTS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


adali.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adali.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
adali.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adali.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
adali.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adali.c.o:  
adali.c.o:  
adali.c.o:  
adali.c.o:  
adali.c.o:   
adali.c.o:   
adali.c.o: 
adali.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adali.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adali.c.o: arbdb++.hxx
adextended.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adextended.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
adextended.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adextended.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
adextended.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adextended.c.o:  
adextended.c.o:  
adextended.c.o:  
adextended.c.o:  
adextended.c.o:  
adextended.c.o:  
adextended.c.o:  
adextended.c.o: 
adextended.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adextended.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adextended.c.o: arbdb++.hxx
admain.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
admain.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
admain.c.o: $(ARBHOME)/INCLUDE/arbdb.h
admain.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
admain.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
admain.c.o:  
admain.c.o:  
admain.c.o:  
admain.c.o:  
admain.c.o:  
admain.c.o:   
admain.c.o:  
admain.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
admain.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
admain.c.o: arbdb++.hxx
adseq.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adseq.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
adseq.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adseq.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
adseq.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adseq.c.o:  
adseq.c.o:  
adseq.c.o:  
adseq.c.o:  
adseq.c.o:  
adseq.c.o:  
adseq.c.o:  
adseq.c.o:   
adseq.c.o:   
adseq.c.o:  
adseq.c.o:  
adseq.c.o:   
adseq.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adseq.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adseq.c.o: arbdb++.hxx
adspecies.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adspecies.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
adspecies.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adspecies.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
adspecies.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adspecies.c.o:  
adspecies.c.o:  
adspecies.c.o:  
adspecies.c.o:  
adspecies.c.o:  
adspecies.c.o:  
adspecies.c.o:  
adspecies.c.o: 
adspecies.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adspecies.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adspecies.c.o: arbdb++.hxx
adt_edit.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adt_edit.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adt_edit.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o:   
adt_edit.c.o:   
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o:  
adt_edit.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adt_edit.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adt_edit.c.o: adtools.hxx arbdb++.hxx
adtali.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adtali.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adtali.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adtali.c.o:  
adtali.c.o:  
adtali.c.o:  
adtali.c.o:  
adtali.c.o:  
adtali.c.o:  
adtali.c.o:   
adtali.c.o:  
adtali.c.o:  
adtali.c.o:  
adtali.c.o: 
adtali.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adtali.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adtali.c.o: adtools.hxx arbdb++.hxx
adtsequence.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
adtsequence.c.o: $(ARBHOME)/INCLUDE/arbdb.h
adtsequence.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
adtsequence.c.o:  
adtsequence.c.o:  
adtsequence.c.o:  
adtsequence.c.o:  
adtsequence.c.o:  
adtsequence.c.o:  
adtsequence.c.o:  
adtsequence.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
adtsequence.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
adtsequence.c.o: adtools.hxx arbdb++.hxx
liste.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
liste.c.o: $(ARBHOME)/INCLUDE/arbdb.h
liste.c.o: $(ARBHOME)/INCLUDE/aw_keysym.hxx
liste.c.o:  
liste.c.o:  
liste.c.o:  
liste.c.o:   
liste.c.o: 
liste.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
liste.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
liste.c.o: arbdb++.hxx
