.SUFFIXES: .o .c

OBJECTS = clustalv.o amenu.o myers.o sequence.o showpair.o \
          upgma.o util.o trees.o gcgcheck.o


$(ARBHOME)/bin/clustalv : $(OBJECTS)
	$(ACC) $(cflags) -o $@ $(OBJECTS) -lm

.c.o:
	$(ACC) $(cflags) -c -o $@ $< $(AINCLUDES)

depend:
	makedepend $(MAKEDEPENDINC) $(OBJECTS:.o=.c)

# DO NOT DELETE THIS LINE -- make depend depends on it.

clustalv.o:  
clustalv.o:  
clustalv.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
clustalv.o:  
clustalv.o:  
clustalv.o:  
clustalv.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
clustalv.o:  
clustalv.o:  clustalv.h general.h matrices.h
amenu.o:  
amenu.o:  
amenu.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
amenu.o:  
amenu.o:  
amenu.o:  
amenu.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
amenu.o:  
amenu.o:  
amenu.o:   clustalv.h
amenu.o: general.h
myers.o:  
myers.o:  
myers.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
myers.o:  
myers.o:  
myers.o:  
myers.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
myers.o:  
myers.o:  clustalv.h general.h
sequence.o:  
sequence.o:  
sequence.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
sequence.o:  
sequence.o:  
sequence.o:  
sequence.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
sequence.o:  
sequence.o:  
sequence.o:   clustalv.h
sequence.o: general.h
showpair.o:  
showpair.o:  
showpair.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
showpair.o:  
showpair.o:  
showpair.o:  
showpair.o:  clustalv.h general.h
upgma.o:  
upgma.o:  
upgma.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
upgma.o:  
upgma.o:  
upgma.o:  
upgma.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
upgma.o:  
upgma.o:  clustalv.h general.h
util.o:  
util.o:  
util.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
util.o:   
util.o:  
util.o:  
util.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
util.o:  
util.o:  
util.o:  
util.o:   
util.o: clustalv.h general.h
trees.o:  
trees.o:  
trees.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
trees.o:  
trees.o:  
trees.o:  
trees.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h
trees.o:  
trees.o:  
trees.o:  
trees.o:  clustalv.h general.h
gcgcheck.o:  
gcgcheck.o:  
gcgcheck.o: 
gcgcheck.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h
gcgcheck.o:  
