.SUFFIXES: .o .cxx

OBJS = CT_part.o CT_hash.o CT_ntree.o CT_rbtree.o CT_dtree.o CT_ctree.o CT_mem.o

$(MAIN): $(OBJS)
	$(AR) $(MAIN) $(OBJS)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
clean:
	rm -f *.o tp a.out
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.

CT_part.o:  
CT_part.o:  
CT_part.o:  
CT_part.o:  
CT_part.o:   
CT_part.o:  
CT_part.o:  
CT_part.o:  
CT_part.o:  $(ARBHOME)/INCLUDE/arbdb.h
CT_part.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_part.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_part.o: $(ARBHOME)/INCLUDE/ad_t_prot.h CT_mem.hxx CT_part.hxx
CT_hash.o:  
CT_hash.o:  
CT_hash.o:  
CT_hash.o:  
CT_hash.o:   
CT_hash.o:  
CT_hash.o:  
CT_hash.o:  
CT_hash.o:  $(ARBHOME)/INCLUDE/arbdb.h
CT_hash.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_hash.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_hash.o: $(ARBHOME)/INCLUDE/ad_t_prot.h CT_mem.hxx CT_part.hxx
CT_hash.o: CT_hash.hxx CT_ntree.hxx
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o:  
CT_ntree.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_ntree.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_ntree.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_ntree.o: $(ARBHOME)/INCLUDE/ad_t_prot.h CT_mem.hxx
CT_ntree.o: CT_part.hxx CT_ntree.hxx
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  
CT_rbtree.o:  $(ARBHOME)/INCLUDE/arbdb.h
CT_rbtree.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_rbtree.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_rbtree.o: $(ARBHOME)/INCLUDE/ad_t_prot.h CT_mem.hxx
CT_rbtree.o: CT_part.hxx CT_ntree.hxx CT_rbtree.hxx
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  
CT_dtree.o:  $(ARBHOME)/INCLUDE/arbdb.h
CT_dtree.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_dtree.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_dtree.o: $(ARBHOME)/INCLUDE/ad_t_prot.h CT_part.hxx
CT_dtree.o: CT_hash.hxx
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  
CT_ctree.o:  $(ARBHOME)/INCLUDE/arbdb.h
CT_ctree.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_ctree.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_ctree.o: $(ARBHOME)/INCLUDE/ad_t_prot.h CT_part.hxx
CT_ctree.o: CT_hash.hxx CT_ntree.hxx CT_rbtree.hxx CT_dtree.hxx
CT_mem.o:  
CT_mem.o:  
CT_mem.o:  
CT_mem.o:  
CT_mem.o:  
CT_mem.o:  
CT_mem.o:  
CT_mem.o:   
CT_mem.o:  
