.SUFFIXES: .o .cxx

OBJS = CT_part.o CT_hash.o CT_ntree.o CT_rbtree.o CT_dtree.o CT_ctree.o CT_mem.o

$(MAIN): $(OBJS)
	$(AR) $(MAIN) $(OBJS)

.cxx.o: 
	$(CPP) $(cflags) -c $< $(CPPINCLUDES)
clean:
	rm -f *.o tp a.out
depend:
	$(MAKEDEPEND) $(MAKEDEPENDINC) $(OBJS:.o=.cxx)
# DO NOT DELETE THIS LINE -- make depend depends on it.


CT_ctree.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_ctree.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
CT_ctree.c.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_ctree.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o:   
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o:  
CT_ctree.c.o: 
CT_ctree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_ctree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_ctree.c.o: CT_dtree.hxx CT_hash.hxx CT_ntree.hxx CT_part.hxx CT_rbtree.hxx
CT_dtree.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_dtree.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
CT_dtree.c.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_dtree.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o:   
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o:  
CT_dtree.c.o: 
CT_dtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_dtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_dtree.c.o: CT_hash.hxx CT_part.hxx
CT_hash.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_hash.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
CT_hash.c.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_hash.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o:   
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o:  
CT_hash.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_hash.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_hash.c.o: CT_hash.hxx CT_mem.hxx CT_ntree.hxx CT_part.hxx
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o:   
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o:  
CT_mem.c.o: 
CT_mem.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_mem.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_ntree.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_ntree.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
CT_ntree.c.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_ntree.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o:   
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o:  
CT_ntree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_ntree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_ntree.c.o: CT_mem.hxx CT_ntree.hxx CT_part.hxx
CT_part.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_part.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
CT_part.c.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_part.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o:   
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o:  
CT_part.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_part.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_part.c.o: CT_mem.hxx CT_part.hxx
CT_rbtree.c.o: $(ARBHOME)/INCLUDE/ad_prot.h
CT_rbtree.c.o: $(ARBHOME)/INCLUDE/ad_t_prot.h
CT_rbtree.c.o: $(ARBHOME)/INCLUDE/arbdb.h
CT_rbtree.c.o: $(ARBHOME)/INCLUDE/arbdbt.h
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o:   
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o:  
CT_rbtree.c.o: 
CT_rbtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stdarg.h
CT_rbtree.c.o: /usr/lib/gcc-lib/i486-suse-linux/2.95.2/include/stddef.h
CT_rbtree.c.o: CT_mem.hxx CT_ntree.hxx CT_part.hxx CT_rbtree.hxx
